/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查 */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前服务版本 */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登录，成功后通过 HttpOnly Cookie 建立会话 */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出，销毁当前会话 */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前登录用户（含角色与模块权限） */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 修改自己的密码（需验证当前密码，成功后注销其他会话） */
        put: operations["changeOwnPassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询本站启用了哪些登录方式（登录页据此渲染，无需鉴权） */
        get: operations["getAuthMethods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/feishu/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 跳转飞书授权页（下发一次性 state Cookie 防 CSRF）
         * @description 浏览器直接导航到此地址，不要用 fetch 调用。
         */
        get: operations["feishuAuthorize"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/feishu/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 飞书授权回调：换取用户身份、建立会话后跳回首页
         * @description 由飞书授权页重定向而来，地址须与开放平台「安全设置」登记的重定向 URL 完全一致。
         */
        get: operations["feishuCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 用户列表（需 users 权限） */
        get: operations["listUsers"];
        put?: never;
        /** 创建用户（需 users 权限；不开放注册，账号只能在此创建） */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除用户（需 users 权限；不能删除自己） */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        /** 修改用户角色或重置密码（需 users 权限；不能改自己的角色） */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 角色列表（需 users 权限） */
        get: operations["listRoles"];
        put?: never;
        /** 创建角色（需 users 权限） */
        post: operations["createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除角色（需 users 权限；内置角色与仍被使用的角色不可删除） */
        delete: operations["deleteRole"];
        options?: never;
        head?: never;
        /** 修改角色名或权限（需 users 权限；内置角色不可修改） */
        patch: operations["updateRole"];
        trace?: never;
    };
    "/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 渠道列表（需 channels 权限） */
        get: operations["listChannels"];
        put?: never;
        /** 创建渠道（需 channels 权限；模型条目建完后在详情页添加） */
        post: operations["createChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 渠道详情（需 channels 权限；含模型条目列表） */
        get: operations["getChannel"];
        put?: never;
        post?: never;
        /** 删除渠道（需 channels 权限；硬删，历史任务持有参数快照不受影响，key 不可恢复） */
        delete: operations["deleteChannel"];
        options?: never;
        head?: never;
        /** 修改渠道基本信息（需 channels 权限；apiKey 缺省=不改、给值=覆盖，写后不可回读） */
        patch: operations["updateChannel"];
        trace?: never;
    };
    "/channels/{id}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 添加模型条目（需 channels 权限） */
        post: operations["addChannelModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{id}/models/{modelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 全量替换模型条目（需 channels 权限；缺省的价格字段即清空为未定价） */
        put: operations["updateChannelModel"];
        post?: never;
        /** 删除模型条目（需 channels 权限；历史任务持有参数快照不受影响） */
        delete: operations["deleteChannelModel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 连通测试（需 channels 权限；对每个已声明协议发 max_tokens=1 最小真实请求，结果落库为该渠道最近一次测试） */
        post: operations["testChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{id}/connectivity/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 连通历史（登录即可；总览延迟曲线数据源，含手动测试与定时探活两种来源） */
        get: operations["getChannelConnectivityHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overview/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 总览渠道卡片（登录即可；渠道基本信息 + 各模型最近终态质量任务得分，得分即时计算不持久化） */
        get: operations["listOverviewChannels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 检查在线更新（需 system 权限；查询 GitHub 最新 Release） */
        get: operations["getUpdateStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/update/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 触发在线更新（需 system 权限；调 GitHub Actions 重新部署指定版本） */
        post: operations["triggerDeploy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/probes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 检测项注册表（需 quality 权限；含元数据供发起页勾选） */
        get: operations["listProbes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quality/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 质量检测任务历史（需 quality 权限；按创建时间倒序，可按状态/渠道筛选） */
        get: operations["listQualityTasks"];
        put?: never;
        /** 创建质量检测任务（需 quality 权限；创建时快照检测对象参数，入队后由 worker 执行） */
        post: operations["createQualityTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quality/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务详情（需 quality 权限；含参数快照与聚合统计） */
        get: operations["getQualityTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quality/tasks/{id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 用例级结果（需 quality 权限；可按判定状态过滤） */
        get: operations["listQualityTaskResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quality/tasks/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 评分板（需 quality 权限；检查点加权评分，按当前注册表口径即时计算，仅终态任务可用） */
        get: operations["getQualityTaskReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quality/tasks/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 导出报告（需 quality 权限；json=证据链自足报告，junit=JUnit XML；仅终态任务可用） */
        get: operations["exportQualityTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quality/tasks/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 取消任务（需 quality 权限；排队或运行中的任务可取消，运行中的中止在途请求） */
        post: operations["cancelQualityTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quality/tasks/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务进度事件流（需 quality 权限；SSE，连接后先推当前快照，任务终态后关闭） */
        get: operations["streamQualityTaskEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stability/probes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 稳定性检测项注册表（需 stability 权限；产出性能指标，无评分检查点） */
        get: operations["listStabilityProbes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stability/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 稳定性检测任务历史（需 stability 权限；按创建时间倒序，可按状态/渠道筛选） */
        get: operations["listStabilityTasks"];
        put?: never;
        /** 创建稳定性检测任务（需 stability 权限；创建时快照检测对象+协议，入队后由 worker 发压） */
        post: operations["createStabilityTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stability/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 稳定性任务详情（需 stability 权限；含参数快照） */
        get: operations["getStabilityTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stability/tasks/{id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 稳定性指标报告（需 stability 权限；档级+overall 聚合，仅终态任务可用） */
        get: operations["getStabilityTaskMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stability/tasks/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 导出稳定性报告（需 stability 权限；json=证据链自足报告，含全量逐请求样本；仅终态任务可用） */
        get: operations["exportStabilityTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stability/tasks/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 取消稳定性任务（需 stability 权限；排队或运行中的任务可取消，运行中的中止在途请求） */
        post: operations["cancelStabilityTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stability/tasks/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 稳定性任务进度事件流（需 stability 权限；SSE，连接后先推当前快照，任务终态后关闭） */
        get: operations["streamStabilityTaskEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        VersionInfo: {
            version: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        /** @description 粗粒度模块权限开关：控制对应页面与该模块全部接口的访问 */
        PermissionMap: {
            channels: boolean;
            quality: boolean;
            stability: boolean;
            users: boolean;
            system: boolean;
        };
        CurrentUser: {
            /** Format: uuid */
            id: string;
            username: string;
            /** @description 飞书账号的姓名，密码账号为空 */
            displayName?: string | null;
            /** @description 飞书头像地址，密码账号为空 */
            avatarUrl?: string | null;
            role: string;
            permissions: components["schemas"]["PermissionMap"];
        };
        /** @description 登录页据此决定渲染哪些入口 */
        AuthMethods: {
            /** @description 是否保留用户名密码登录（管理员兜底通道） */
            password: boolean;
            /** @description 是否已配置飞书 OAuth 登录 */
            feishu: boolean;
        };
        /** @enum {string} */
        AuthSource: "password" | "feishu";
        User: {
            /** Format: uuid */
            id: string;
            username: string;
            /** Format: uuid */
            roleId: string;
            roleName: string;
            authSource: components["schemas"]["AuthSource"];
            /** Format: date-time */
            createdAt: string;
        };
        UserCreate: {
            username: string;
            password: string;
            /** Format: uuid */
            roleId: string;
        };
        UserUpdate: {
            /** Format: uuid */
            roleId?: string;
            password?: string;
        };
        Role: {
            /** Format: uuid */
            id: string;
            name: string;
            builtIn: boolean;
            permissions: components["schemas"]["PermissionMap"];
        };
        RoleCreate: {
            name: string;
            permissions: components["schemas"]["PermissionMap"];
        };
        RoleUpdate: {
            name?: string;
            permissions?: components["schemas"]["PermissionMap"];
        };
        UpdateStatus: {
            currentVersion: string;
            /** @description 服务器是否配置了 GitHub Token（未配置时无法检查/触发更新） */
            tokenConfigured: boolean;
            updateAvailable: boolean;
            latestVersion?: string;
            releaseNotes?: string;
            /** Format: date-time */
            publishedAt?: string;
        };
        DeployRequest: {
            /** @description 要部署的版本 tag（须是已存在的 GitHub Release） */
            tag: string;
        };
        /**
         * @description 渠道支持的接口协议
         * @enum {string}
         */
        Protocol: "openai_chat" | "openai_responses" | "anthropic_messages";
        /**
         * @description 渠道定价币种（仅标注，不做汇率换算）
         * @enum {string}
         */
        Currency: "USD" | "CNY";
        Channel: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description 填到版本段（如 https://api.example.com/v1），平台按协议拼固定末段 */
            baseUrl: string;
            /** @description API key 脱敏前缀（key 写后不可回读） */
            keyPrefix: string;
            protocols: components["schemas"]["Protocol"][];
            currency: components["schemas"]["Currency"];
            note: string;
            /** @description 停用后不可选入新检测任务，配置与 key 保留 */
            disabled: boolean;
            modelCount: number;
            lastTest?: components["schemas"]["ConnectivityTest"];
            /** @description 定时探活间隔分钟（1-1440）；缺省=未开启 */
            probeIntervalMinutes?: number;
            /**
             * Format: uuid
             * @description 定时探活用的模型条目；条目被删自动置空、调度停摆
             */
            probeModelId?: string;
            /** Format: date-time */
            createdAt: string;
        };
        ChannelDetail: components["schemas"]["Channel"] & {
            models: components["schemas"]["ModelEntry"][];
        };
        ChannelCreate: {
            name: string;
            /** @description 填到版本段（如 https://api.example.com/v1），末尾斜杠会被自动去除 */
            baseUrl: string;
            apiKey: string;
            protocols: components["schemas"]["Protocol"][];
            currency?: components["schemas"]["Currency"];
            note?: string;
        };
        ChannelUpdate: {
            name?: string;
            baseUrl?: string;
            /** @description 缺省=不改；给值=整体覆盖 */
            apiKey?: string;
            protocols?: components["schemas"]["Protocol"][];
            currency?: components["schemas"]["Currency"];
            note?: string;
            disabled?: boolean;
            /** @description 定时探活间隔分钟；须与 probeModelId 成对提交整体覆盖，0=关闭（coalesce 语义写不了 null，故用 0 哨兵） */
            probeIntervalMinutes?: number;
            /**
             * Format: uuid
             * @description 定时探活模型条目（须属本渠道）；probeIntervalMinutes=0 时可缺省
             */
            probeModelId?: string;
        };
        ModelEntry: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description 每 1M token 输入单价（币种见渠道）；三个价格字段全缺省=未定价 */
            inputPrice?: number;
            outputPrice?: number;
            cachedInputPrice?: number;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description 输入/输出价须成对出现；缓存读价只能在前两者存在时给出（服务端校验） */
        ModelEntryUpsert: {
            name: string;
            inputPrice?: number;
            outputPrice?: number;
            cachedInputPrice?: number;
        };
        ConnectivityTestRequest: {
            /**
             * Format: uuid
             * @description 用哪个模型条目发探测请求
             */
            modelId: string;
        };
        ConnectivityTest: {
            /** Format: date-time */
            testedAt: string;
            /** @description 当时用于探测的模型名（快照，不随模型条目改名变化） */
            model: string;
            results: components["schemas"]["ConnectivityResult"][];
        };
        ConnectivityResult: {
            protocol: components["schemas"]["Protocol"];
            ok: boolean;
            /** @description 上游 HTTP 状态码（网络层失败时缺省） */
            status?: number;
            /** @description 首字延迟毫秒（流式首个数据帧到达；失败时缺省） */
            ttftMs?: number;
            /** @description 失败摘要（超时/连接错误/上游错误体截断） */
            error?: string;
        };
        /**
         * @description 探测来源：manual=手动测试、scheduled=定时探活
         * @enum {string}
         */
        ConnectivitySource: "manual" | "scheduled";
        /** @description 连通历史点：一行=（一次测试 × 一协议），同次测试各协议行 testedAt 严格一致，前端按其分组还原一次测试 */
        ConnectivityHistoryPoint: {
            /** Format: date-time */
            testedAt: string;
            /** @description 当时探测用的模型名快照 */
            model: string;
            source: components["schemas"]["ConnectivitySource"];
            protocol: components["schemas"]["Protocol"];
            ok: boolean;
            /** @description 首字延迟毫秒；失败时缺省（曲线在此断点留白） */
            ttftMs?: number;
        };
        /** @description 总览卡片单模型得分行：该渠道 × 模型名快照的最近一个终态质量任务即时计算；taskStatus 非 succeeded 时得分基于不完整采样，前端须挂状态标注 */
        OverviewModelScore: {
            /** @description 模型名快照（与任务快照、连通历史同口径） */
            model: string;
            /**
             * Format: uuid
             * @description 任务快照里的模型条目 id（老任务缺省；用于匹配默认探活模型）
             */
            modelEntryId?: string;
            /** Format: uuid */
            taskId: string;
            taskStatus: components["schemas"]["TaskStatus"];
            /** Format: date-time */
            finishedAt?: string;
            /** @description 总分 0-100，口径与任务报告一致；无已采样检查点时缺省 */
            score?: number;
        };
        OverviewChannel: components["schemas"]["Channel"] & {
            /** @description 有终态质量任务的模型得分行（按模型名去重取最近一次） */
            models: components["schemas"]["OverviewModelScore"][];
        };
        ProbeInfo: {
            /** @description 检测项唯一标识（如 tool_call_json_schema） */
            id: string;
            /** @description 中文显示名 */
            name: string;
            description: string;
            /** @description 适用协议（渠道须至少声明其中之一） */
            protocols: components["schemas"]["Protocol"][];
            /** @description 是否需要对照渠道 */
            needsControl: boolean;
            /** @description 是否要求目标模型已定价 */
            needsPricing: boolean;
            /** @description 全量用例数 */
            caseCount: number;
            /** @description 每用例请求数（如 toolschema 非流式+流式各一次 = 2），用于前端估算请求量 */
            requestsPerCase: number;
            /** @description 是否受任务参数「用例数上限」影响（固定请求矩阵的检测项为 false） */
            supportsMaxCases: boolean;
        };
        /** @enum {string} */
        TaskStatus: "queued" | "running" | "succeeded" | "failed" | "canceled";
        /**
         * @description 用例判定：rejected=请求被上游拒绝（HTTP/传输错误）；violated=响应到手但不合规；passed=合规；collected=已采集·待评估（跨行断言检测项运行中的中间态，只含原始计数不含结论，任务结束后必被终态覆盖）
         * @enum {string}
         */
        CaseStatus: "passed" | "rejected" | "violated" | "collected";
        /** @enum {string} */
        CaseMode: "non_stream" | "stream";
        QualityTaskParams: {
            /**
             * @description 任务内请求并发数
             * @default 4
             */
            concurrency: number;
            /**
             * @description 失败用例重跑轮数（末次结果为准）
             * @default 2
             */
            reruns: number;
            /** @description 用例数上限（缺省=全量；超过检测项全量数时按全量算） */
            maxCases?: number;
        };
        QualityTaskCreate: {
            /** Format: uuid */
            channelId: string;
            /** Format: uuid */
            modelEntryId: string;
            /** @description 勾选的检测项 id 集合 */
            probes: string[];
            params?: components["schemas"]["QualityTaskParams"];
        };
        /** @description 检测对象参数快照（任务创建时定格，不受渠道后续编辑/删除影响；绝不含 API key） */
        TaskTarget: {
            /**
             * Format: uuid
             * @description 原渠道 id（渠道被删后仅作历史参考）
             */
            channelId?: string;
            channelName: string;
            baseUrl: string;
            /** Format: uuid */
            modelEntryId?: string;
            model: string;
            protocols: components["schemas"]["Protocol"][];
            currency?: components["schemas"]["Currency"];
            inputPrice?: number;
            outputPrice?: number;
            cachedInputPrice?: number;
        };
        TaskStatBucket: {
            name: string;
            total: number;
            passed: number;
            rejected: number;
            violated: number;
            /** @description 已采集·待评估行数（仅运行中非零） */
            collected: number;
        };
        TaskStats: {
            total: number;
            passed: number;
            rejected: number;
            violated: number;
            /** @description 已采集·待评估行数（仅运行中非零） */
            collected: number;
            byMode: components["schemas"]["TaskStatBucket"][];
            /** @description 按选例理由（selection_reason）分桶 */
            byReason: components["schemas"]["TaskStatBucket"][];
        };
        QualityTask: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["TaskStatus"];
            target: components["schemas"]["TaskTarget"];
            probes: string[];
            /** @description 生效参数（缺省项已填入默认值） */
            params: components["schemas"]["QualityTaskParams"];
            progressTotal: number;
            progressDone: number;
            /** @description 任务级失败原因（用例级失败不算任务失败） */
            error?: string;
            /** @description 创建者用户名（用户被删后缺省） */
            createdBy?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
            /** @description 聚合统计（仅详情接口返回，任务未产生结果时缺省） */
            stats?: components["schemas"]["TaskStats"];
            /** @description 总分 0-100；仅列表接口对终态任务返回，按当前检查点注册表口径即时计算、绝不持久化；排队/运行中或无已采样检查点时缺省 */
            score?: number;
        };
        QualityTaskList: {
            items: components["schemas"]["QualityTask"][];
            total: number;
        };
        QualityCaseResult: {
            probe: string;
            /** @description 语料套件名（如 TestEnforcerCases） */
            suite: string;
            /** @description 套件内行号（1 起，与 KVV 官方报告对齐） */
            line: number;
            mode: components["schemas"]["CaseMode"];
            selectionReason: string;
            status: components["schemas"]["CaseStatus"];
            /** @description 失败摘要（校验错误/上游错误体截断；通过时为空） */
            message: string;
            httpStatus?: number;
            latencyMs?: number;
            /** @description 模型最终产出的工具参数原文（截断存储） */
            arguments?: string;
            attempts: number;
        };
        /** @description 一个评分检查点的聚合结果；得分 = passed/total × 100（rejected 与 violated 均计失败） */
        CheckpointScore: {
            /** @description 检查点稳定标识（检测项元数据声明） */
            id: string;
            name: string;
            /** @description 同一检测项内的相对权重 */
            weight: number;
            total: number;
            passed: number;
            rejected: number;
            violated: number;
            /** @description 0-100；未采样（total=0，如被用例上限截掉）时缺省且不参与加权 */
            score?: number;
        };
        ProbeScore: {
            probeId: string;
            /** @description 检测项中文名（快照自注册表；检测项已下架时回退为 id） */
            probeName: string;
            /** @description 检查点加权平均（0-100）；全部检查点未采样时缺省 */
            score?: number;
            checkpoints: components["schemas"]["CheckpointScore"][];
        };
        /** @description 评分板：按「检查点 + 权重」模型即时计算——检查点得分=命中用例通过占比，检测项得分=检查点加权平均，总分=各检测项等权平均。原始判定以用例级结果为准，评分是其视图。 */
        QualityReport: {
            /** Format: uuid */
            taskId: string;
            status: components["schemas"]["TaskStatus"];
            /** @description 总分 0-100；无任何已采样检查点时缺省 */
            score?: number;
            /** @description 任务非正常结束（failed/canceled），评分仅基于已采集数据 */
            incomplete?: boolean;
            probes: components["schemas"]["ProbeScore"][];
            /** Format: date-time */
            generatedAt: string;
        };
        /** @description 证据链自足的 JSON 导出：任务快照 + 评分板 + 全量用例级结果，脱离平台可独立审计 */
        QualityExport: {
            /** @description 固定 "assay" */
            tool: string;
            /** @description 导出时服务端版本 */
            version: string;
            task: components["schemas"]["QualityTask"];
            report: components["schemas"]["QualityReport"];
            results: components["schemas"]["QualityCaseResult"][];
        };
        /** @description SSE data 帧载荷 */
        TaskProgressEvent: {
            /** Format: uuid */
            taskId: string;
            status: components["schemas"]["TaskStatus"];
            done: number;
            total: number;
        };
        Error: {
            error: string;
        };
        /** @description 稳定性检测项元数据（产出性能指标，无评分检查点） */
        StabilityProbeInfo: {
            /** @description 检测项唯一标识（如 concurrency_ladder） */
            id: string;
            name: string;
            description: string;
            /** @description 适用协议（空=全适用，前端展示为三协议皆可） */
            protocols: components["schemas"]["Protocol"][];
            /** @description 按默认参数的最坏预估请求数（前端据实选参数自行重算展示） */
            estRequests: number;
        };
        /** @description 稳定性任务参数：实选协议 + 各 probe 档位 + 全局成本硬闸 */
        StabilityTaskParams: {
            /** @description 本任务实选协议（写入快照；须为渠道声明协议之一） */
            protocol?: components["schemas"]["Protocol"];
            /**
             * @description 阶梯并发的并发档序列（闭环）
             * @default [
             *       1,
             *       2,
             *       4,
             *       8,
             *       16
             *     ]
             */
            concurrencyLadder: number[];
            /**
             * @description 每档计入统计的请求数
             * @default 20
             */
            requestsPerStage: number;
            /**
             * @description 每档预热请求数（评估时剔除，不计入指标）；缺省 0（不预热）
             * @default 0
             */
            warmupPerStage: number;
            /**
             * @description 每请求生成上限（max_tokens 砝码，控制单请求耗时与成本）
             * @default 64
             */
            ladderMaxTokens: number;
            /**
             * @description RPM 实测起始到达率（req/s，开环）
             * @default 2
             */
            rpmStartRate: number;
            /**
             * @description RPM 探测速率护栏上限（req/s）；升到此仍不限速则报「边界≥上限」
             * @default 20
             */
            rpmMaxRate: number;
            /**
             * @description RPM 每档发压时长（秒）
             * @default 10
             */
            rpmStageSec: number;
            /**
             * @description RPM 在途请求上限（防雪崩兜底）
             * @default 128
             */
            rpmMaxInFlight: number;
            /**
             * @description RPM 每请求生成上限（只关心请求速率，取小）
             * @default 16
             */
            rpmMaxTokens: number;
            /**
             * @description 判定某档触发限速的 429 占比阈值（0-1）
             * @default 0.1
             */
            rpmLimitThreshold: number;
            /**
             * @description 找到限速档后二分细化真实边界的步数
             * @default 4
             */
            rpmBinarySteps: number;
            /**
             * @description TPM 实测起始 token 到达率（token/s，开环；换算请求速率发压）
             * @default 200
             */
            tpmStartRate: number;
            /**
             * @description TPM 探测 token 速率护栏上限（token/s）；升到此仍不限速则报「边界≥上限」
             * @default 2000
             */
            tpmMaxRate: number;
            /**
             * @description TPM 每档发压时长（秒）
             * @default 10
             */
            tpmStageSec: number;
            /**
             * @description TPM 在途请求上限（防雪崩兜底）
             * @default 128
             */
            tpmMaxInFlight: number;
            /**
             * @description TPM 每请求 max_tokens 砝码（顶格数数 prompt 保证打满输出；输入+输出都计）
             * @default 256
             */
            tpmMaxTokensPerReq: number;
            /**
             * @description 判定某档触发限速的 429 占比阈值（0-1）
             * @default 0.1
             */
            tpmLimitThreshold: number;
            /**
             * @description 找到限速档后二分细化真实 token 速率边界的步数
             * @default 4
             */
            tpmBinarySteps: number;
            /**
             * @description 全局请求硬闸；累计达到即收敛停止
             * @default 2000
             */
            maxTotalRequests: number;
            /**
             * @description 全局 token 硬闸；累计达到即收敛停止
             * @default 2000000
             */
            maxTotalTokens: number;
            /**
             * @description 单请求超时（毫秒）
             * @default 60000
             */
            requestTimeoutMs: number;
        };
        StabilityTaskCreate: {
            /** Format: uuid */
            channelId: string;
            /** Format: uuid */
            modelEntryId: string;
            /** @description 勾选的稳定性检测项 id 集合 */
            probes: string[];
            params: components["schemas"]["StabilityTaskParams"];
        };
        StabilityTask: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["TaskStatus"];
            target: components["schemas"]["TaskTarget"];
            probes: string[];
            /** @description 生效参数（缺省项已填入默认值） */
            params: components["schemas"]["StabilityTaskParams"];
            progressTotal: number;
            progressDone: number;
            error?: string;
            createdBy?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
        };
        StabilityTaskList: {
            items: components["schemas"]["StabilityTask"][];
            total: number;
        };
        /** @description 一组延迟观测的分位数摘要（评估期确定性计算，单位毫秒） */
        StabilityPercentiles: {
            p50: number;
            p95: number;
            p99: number;
            min: number;
            max: number;
            avg: number;
        };
        /** @description 一个（probe×档位）的指标集 */
        StabilityMetrics: {
            /** @description 计入统计的请求数（已剔除预热） */
            requests: number;
            errors: number;
            errorRate: number;
            ttftMs?: components["schemas"]["StabilityPercentiles"];
            ttfbMs?: components["schemas"]["StabilityPercentiles"];
            totalMs?: components["schemas"]["StabilityPercentiles"];
            /** @description 达成吞吐（请求/秒，按样本时间窗计） */
            throughputRps?: number;
            /** @description 输出 token 吞吐（token/秒） */
            tokensPerSec?: number;
            /** @description 各错误分类计数 */
            byErrorClass?: {
                [key: string]: number;
            };
            /** @description 阶梯并发档的并发数（其它 probe 缺省） */
            concurrency?: number;
            /** @description 开环档目标到达率（req/s） */
            targetRate?: number;
            /** @description 开环档实际达成到达率（req/s，在途封顶会低于目标） */
            achievedRate?: number;
            /** @description 开环档 429 占比是否判定为触发限速 */
            rateLimited?: boolean;
            /** @description __overall__ RPM 收敛的可持续边界（请求/分钟） */
            convergedRpm?: number;
            /** @description __overall__ 探到速率护栏顶仍未限速（真实边界≥护栏） */
            reachedCap?: boolean;
            /** @description TPM 开环档目标 token 到达率（token/s） */
            targetTokenRate?: number;
            /** @description TPM 开环档实测 token 吞吐（token/s，输入+输出都计） */
            achievedTokenRate?: number;
            /** @description __overall__ TPM 收敛的可持续边界（token/分钟） */
            convergedTpm?: number;
            /** @description 最近一次响应携带的限速头快照（x-ratelimit-*\/anthropic-ratelimit-*\/retry-after） */
            rateLimitHeaders?: {
                [key: string]: string;
            };
        };
        /** @description 一档（或 __overall__ probe 级）的评估结果 */
        StabilityStageMetric: {
            probe: string;
            /** @description 档位标识；__overall__ 为 probe 级汇总 */
            stage: string;
            /** @description 档序号；__overall__ 为 -1 */
            stageIndex: number;
            metrics: components["schemas"]["StabilityMetrics"];
        };
        /** @description 稳定性指标报告：档级 + overall 聚合，口径见 footnotes */
        StabilityReport: {
            /** Format: uuid */
            taskId: string;
            status: components["schemas"]["TaskStatus"];
            protocol: components["schemas"]["Protocol"];
            /** @description 任务非正常结束（failed/canceled），指标仅基于已采集样本 */
            incomplete?: boolean;
            stages: components["schemas"]["StabilityStageMetric"][];
            /** @description 测量口径脚注（TTFT 起点、预热剔除、分位数算法等） */
            footnotes?: string[];
            /** Format: date-time */
            generatedAt: string;
        };
        /** @description 一次压测请求的逐请求原始时序（证据链源；失败样本延迟/计量字段缺省） */
        StabilitySample: {
            probe: string;
            stage: string;
            stageIndex: number;
            seq: number;
            protocol: components["schemas"]["Protocol"];
            /** Format: date-time */
            dispatchedAt: string;
            ok: boolean;
            httpStatus?: number;
            errorClass?: string;
            error?: string;
            ttfbMs?: number;
            ttftMs?: number;
            totalMs?: number;
            inputTokens?: number;
            outputTokens?: number;
            warmup: boolean;
        };
        /** @description 证据链自足的 JSON 导出：任务快照 + 指标报告 + 全量逐请求样本 */
        StabilityExport: {
            tool: string;
            version: string;
            task: components["schemas"]["StabilityTask"];
            report: components["schemas"]["StabilityReport"];
            samples: components["schemas"]["StabilitySample"][];
        };
    };
    responses: {
        /** @description 请求非法 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 未登录或会话已过期 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 无权访问该模块 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 资源不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        IdPath: string;
        ModelIdPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务正常 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 正在运行的服务版本号 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功，Set-Cookie 下发会话 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 请求格式错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 用户名或密码错误 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 本站已关闭密码登录 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已登出（无论此前是否持有有效会话） */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前用户信息 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    changeOwnPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description 修改成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getAuthMethods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 可用登录方式 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMethods"];
                };
            };
        };
    };
    feishuAuthorize: {
        parameters: {
            query?: {
                /** @description 登录成功后要回到的站内路径（如 /quality/abc）。只接受以单个 / 开头的相对路径， 其余一律忽略并回落到首页——防开放重定向。 */
                next?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 重定向到飞书授权页 */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 未配置飞书登录 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    feishuCallback: {
        parameters: {
            query?: {
                /** @description 授权码，5 分钟有效且仅可用一次 */
                code?: string;
                /** @description 发起授权时下发的一次性随机串 */
                state?: string;
                /** @description 用户取消授权等失败场景由飞书回传 */
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功跳首页并 Set-Cookie 建立会话；失败跳 /login 并在 query 带错误原因 */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 全部用户 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description 用户名已存在 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description 修改后的用户 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 全部角色 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleCreate"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description 角色名已存在 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description 角色仍被用户使用 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdate"];
            };
        };
        responses: {
            /** @description 修改后的角色 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listChannels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 全部渠道（含停用的，不含模型明细） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Channel"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelCreate"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Channel"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description 渠道名已存在 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 渠道详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功（连同其模型条目） */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelUpdate"];
            };
        };
        responses: {
            /** @description 修改后的渠道 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Channel"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description 渠道名已存在 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    addChannelModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelEntryUpsert"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelEntry"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description 该渠道下模型名已存在 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateChannelModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
                modelId: components["parameters"]["ModelIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelEntryUpsert"];
            };
        };
        responses: {
            /** @description 替换后的模型条目 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelEntry"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description 该渠道下模型名已存在 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteChannelModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
                modelId: components["parameters"]["ModelIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    testChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectivityTestRequest"];
            };
        };
        responses: {
            /** @description 各协议连通结果（上游拒绝/超时也是正常结果，体现在 ok=false） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectivityTest"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getChannelConnectivityHistory: {
        parameters: {
            query?: {
                /** @description 回看窗口小时数 */
                hours?: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 时间升序的历史点列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ConnectivityHistoryPoint"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listOverviewChannels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 渠道卡片列表（按创建时间排序） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["OverviewChannel"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getUpdateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前版本与最新版本信息 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description GitHub API 请求失败 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    triggerDeploy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeployRequest"];
            };
        };
        responses: {
            /** @description 已触发部署流水线，稍后轮询 /version 确认切换 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description GitHub API 请求失败 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listProbes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 全部已注册检测项 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeInfo"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listQualityTasks: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description 按任务状态筛选；缺省不过滤 */
                status?: components["schemas"]["TaskStatus"];
                /** @description 按渠道筛选；缺省不过滤（渠道删除后其任务 channel_id 置空，仅在不过滤时可见） */
                channelId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务列表分页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityTaskList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createQualityTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QualityTaskCreate"];
            };
        };
        responses: {
            /** @description 任务已创建并入队 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityTask"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description 渠道已停用或不支持检测项所需协议 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getQualityTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityTask"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listQualityTaskResults: {
        parameters: {
            query?: {
                status?: components["schemas"]["CaseStatus"];
            };
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用例结果列表（按套件/行号/模式排序） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityCaseResult"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getQualityTaskReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 评分板 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityReport"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description 任务尚未结束，暂无评分 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    exportQualityTask: {
        parameters: {
            query: {
                format: "json" | "junit";
            };
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 报告文件（Content-Disposition attachment） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityExport"];
                    "application/xml": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description 任务尚未结束，暂无报告 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    cancelQualityTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取消后的任务 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityTask"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description 任务已结束，不可取消 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    streamQualityTaskEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream，每帧 data 为 TaskProgressEvent 的 JSON */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listStabilityProbes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 全部已注册稳定性检测项 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StabilityProbeInfo"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listStabilityTasks: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description 按任务状态筛选；缺省不过滤 */
                status?: components["schemas"]["TaskStatus"];
                /** @description 按渠道筛选；缺省不过滤（渠道删除后其任务 channel_id 置空，仅在不过滤时可见） */
                channelId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务列表分页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StabilityTaskList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createStabilityTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StabilityTaskCreate"];
            };
        };
        responses: {
            /** @description 任务已创建并入队 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StabilityTask"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description 渠道已停用或不支持所选协议 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getStabilityTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StabilityTask"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getStabilityTaskMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 指标报告 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StabilityReport"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description 任务尚未结束，暂无指标报告 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    exportStabilityTask: {
        parameters: {
            query: {
                format: "json";
            };
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 报告文件（Content-Disposition attachment） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StabilityExport"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description 任务尚未结束，暂无报告 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    cancelStabilityTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取消后的任务 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StabilityTask"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description 任务已结束，不可取消 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    streamStabilityTaskEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream，每帧 data 为 TaskProgressEvent 的 JSON */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
