// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Channel struct {
	ID                   uuid.UUID
	Name                 string
	BaseUrl              string
	ApiKey               string
	KeyPrefix            string
	Protocols            []string
	Currency             string
	Note                 string
	Disabled             bool
	LastTest             []byte
	CreatedAt            time.Time
	ProbeIntervalMinutes pgtype.Int4
	ProbeModelID         pgtype.UUID
}

type ChannelModel struct {
	ID               uuid.UUID
	ChannelID        uuid.UUID
	Name             string
	InputPrice       *float64
	OutputPrice      *float64
	CachedInputPrice *float64
	CreatedAt        time.Time
}

type ConnectivityResult struct {
	ID         int64
	ChannelID  uuid.UUID
	Model      string
	Source     string
	Protocol   string
	Ok         bool
	HttpStatus pgtype.Int4
	TtftMs     pgtype.Int4
	Error      *string
	TestedAt   time.Time
}

type Role struct {
	ID          uuid.UUID
	Name        string
	BuiltIn     bool
	Permissions []byte
	CreatedAt   time.Time
}

type Session struct {
	TokenHash []byte
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

type StabilityMetric struct {
	ID         int64
	TaskID     uuid.UUID
	Probe      string
	Stage      string
	StageIndex int32
	Metrics    []byte
	CreatedAt  time.Time
}

type StabilitySample struct {
	ID           int64
	TaskID       uuid.UUID
	Probe        string
	Stage        string
	StageIndex   int32
	Seq          int32
	Protocol     string
	DispatchedAt time.Time
	TtfbMs       pgtype.Int4
	TtfdMs       pgtype.Int4
	TtftMs       pgtype.Int4
	TotalMs      pgtype.Int4
	Ok           bool
	HttpStatus   pgtype.Int4
	HttpProto    *string
	ErrorClass   *string
	Error        *string
	InputTokens  pgtype.Int4
	OutputTokens pgtype.Int4
	CachedTokens pgtype.Int4
	Warmup       bool
}

type Task struct {
	ID            uuid.UUID
	Kind          string
	Status        string
	ChannelID     pgtype.UUID
	Target        []byte
	Probes        []string
	Params        []byte
	ProgressTotal int32
	ProgressDone  int32
	RiverJobID    pgtype.Int8
	Error         *string
	CreatedBy     pgtype.UUID
	CreatedAt     time.Time
	StartedAt     pgtype.Timestamptz
	FinishedAt    pgtype.Timestamptz
}

type TaskCaseResult struct {
	ID              int64
	TaskID          uuid.UUID
	Probe           string
	Suite           string
	Line            int32
	Mode            string
	SelectionReason string
	Status          string
	Message         string
	HttpStatus      pgtype.Int4
	LatencyMs       pgtype.Int4
	Arguments       *string
	Attempts        int32
	CreatedAt       time.Time
}

type User struct {
	ID            uuid.UUID
	Username      string
	PasswordHash  *string
	CreatedAt     time.Time
	RoleID        uuid.UUID
	FeishuUnionID *string
	FeishuOpenID  *string
	DisplayName   *string
	AvatarUrl     *string
}
