// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateCaseResultsByTaskIDs = `-- name: AggregateCaseResultsByTaskIDs :many
select task_id, probe, suite, mode, status, count(*) as n
from task_case_results
where task_id = any ($1::uuid[])
group by task_id, probe, suite, mode, status
`

type AggregateCaseResultsByTaskIDsRow struct {
	TaskID uuid.UUID
	Probe  string
	Suite  string
	Mode   string
	Status string
	N      int64
}

// 列表页/总览批量评分：一条 SQL 拿回一批任务的分组计数，Go 侧按检查点加权，
// 避免逐任务全量捞用例行（408 行 × 20 任务）
func (q *Queries) AggregateCaseResultsByTaskIDs(ctx context.Context, taskIds []uuid.UUID) ([]AggregateCaseResultsByTaskIDsRow, error) {
	rows, err := q.db.Query(ctx, aggregateCaseResultsByTaskIDs, taskIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregateCaseResultsByTaskIDsRow
	for rows.Next() {
		var i AggregateCaseResultsByTaskIDsRow
		if err := rows.Scan(
			&i.TaskID,
			&i.Probe,
			&i.Suite,
			&i.Mode,
			&i.Status,
			&i.N,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggregateTaskCaseResults = `-- name: AggregateTaskCaseResults :many
select mode as bucket_mode, selection_reason as bucket_reason, status, count(*) as n
from task_case_results
where task_id = $1
group by mode, selection_reason, status
`

type AggregateTaskCaseResultsRow struct {
	BucketMode   string
	BucketReason string
	Status       string
	N            int64
}

// 三个维度一次取回：dimension=mode/reason 各一组分桶，前端聚合总数
func (q *Queries) AggregateTaskCaseResults(ctx context.Context, taskID uuid.UUID) ([]AggregateTaskCaseResultsRow, error) {
	rows, err := q.db.Query(ctx, aggregateTaskCaseResults, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregateTaskCaseResultsRow
	for rows.Next() {
		var i AggregateTaskCaseResultsRow
		if err := rows.Scan(
			&i.BucketMode,
			&i.BucketReason,
			&i.Status,
			&i.N,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelTask = `-- name: CancelTask :execrows
update tasks set status = 'canceled', finished_at = now()
where id = $1 and status in ('queued', 'running')
`

// 排队或运行中可取消；running 的中断由 river JobCancel 通知 worker 取消 ctx
func (q *Queries) CancelTask(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelTask, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countTasks = `-- name: CountTasks :one
select count(*) from tasks
where kind = $1
  and ($2::text is null or status = $2::text)
  and ($3::uuid is null or channel_id = $3::uuid)
`

type CountTasksParams struct {
	Kind      string
	Status    *string
	ChannelID pgtype.UUID
}

func (q *Queries) CountTasks(ctx context.Context, arg CountTasksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTasks, arg.Kind, arg.Status, arg.ChannelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
select count(*) from users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByRole = `-- name: CountUsersByRole :one
select count(*) from users where role_id = $1
`

func (q *Queries) CountUsersByRole(ctx context.Context, roleID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByRole, roleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChannel = `-- name: CreateChannel :one
insert into channels (name, base_url, api_key, key_prefix, protocols, currency, note)
values ($1, $2, $3, $4, $5, $6, $7)
returning id
`

type CreateChannelParams struct {
	Name      string
	BaseUrl   string
	ApiKey    string
	KeyPrefix string
	Protocols []string
	Currency  string
	Note      string
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKey,
		arg.KeyPrefix,
		arg.Protocols,
		arg.Currency,
		arg.Note,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createChannelModel = `-- name: CreateChannelModel :one
insert into channel_models (channel_id, name, input_price, output_price, cached_input_price)
values ($1, $2, $3, $4, $5)
returning id, name, input_price, output_price, cached_input_price, created_at
`

type CreateChannelModelParams struct {
	ChannelID        uuid.UUID
	Name             string
	InputPrice       *float64
	OutputPrice      *float64
	CachedInputPrice *float64
}

type CreateChannelModelRow struct {
	ID               uuid.UUID
	Name             string
	InputPrice       *float64
	OutputPrice      *float64
	CachedInputPrice *float64
	CreatedAt        time.Time
}

func (q *Queries) CreateChannelModel(ctx context.Context, arg CreateChannelModelParams) (CreateChannelModelRow, error) {
	row := q.db.QueryRow(ctx, createChannelModel,
		arg.ChannelID,
		arg.Name,
		arg.InputPrice,
		arg.OutputPrice,
		arg.CachedInputPrice,
	)
	var i CreateChannelModelRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InputPrice,
		&i.OutputPrice,
		&i.CachedInputPrice,
		&i.CreatedAt,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
insert into roles (name, permissions)
values ($1, $2)
returning id, name, built_in, permissions
`

type CreateRoleParams struct {
	Name        string
	Permissions []byte
}

type CreateRoleRow struct {
	ID          uuid.UUID
	Name        string
	BuiltIn     bool
	Permissions []byte
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (CreateRoleRow, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Name, arg.Permissions)
	var i CreateRoleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BuiltIn,
		&i.Permissions,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec
insert into sessions (token_hash, user_id, expires_at)
values ($1, $2, $3)
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const createTask = `-- name: CreateTask :one
insert into tasks (kind, channel_id, target, probes, params, progress_total, created_by)
values ($1, $2, $3, $4, $5, $6, $7)
returning id, created_at
`

type CreateTaskParams struct {
	Kind          string
	ChannelID     pgtype.UUID
	Target        []byte
	Probes        []string
	Params        []byte
	ProgressTotal int32
	CreatedBy     pgtype.UUID
}

type CreateTaskRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.Kind,
		arg.ChannelID,
		arg.Target,
		arg.Probes,
		arg.Params,
		arg.ProgressTotal,
		arg.CreatedBy,
	)
	var i CreateTaskRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createUser = `-- name: CreateUser :one
insert into users (username, password_hash, role_id)
values ($1, $2, $3)
returning id
`

type CreateUserParams struct {
	Username     string
	PasswordHash *string
	RoleID       uuid.UUID
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash, arg.RoleID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteChannel = `-- name: DeleteChannel :execrows
delete from channels where id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteChannelModel = `-- name: DeleteChannelModel :execrows
delete from channel_models where id = $1 and channel_id = $2
`

type DeleteChannelModelParams struct {
	ID        uuid.UUID
	ChannelID uuid.UUID
}

func (q *Queries) DeleteChannelModel(ctx context.Context, arg DeleteChannelModelParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannelModel, arg.ID, arg.ChannelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
delete from sessions where expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldConnectivityResults = `-- name: DeleteOldConnectivityResults :execrows
delete from connectivity_results where tested_at < now() - interval '7 days'
`

// 历史保留 7 天：曲线窗口最长 168 小时，更久的数据无消费方
func (q *Queries) DeleteOldConnectivityResults(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldConnectivityResults)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOtherUserSessions = `-- name: DeleteOtherUserSessions :exec
delete from sessions where user_id = $1 and token_hash <> $2
`

type DeleteOtherUserSessionsParams struct {
	UserID    uuid.UUID
	TokenHash []byte
}

func (q *Queries) DeleteOtherUserSessions(ctx context.Context, arg DeleteOtherUserSessionsParams) error {
	_, err := q.db.Exec(ctx, deleteOtherUserSessions, arg.UserID, arg.TokenHash)
	return err
}

const deleteRole = `-- name: DeleteRole :execrows
delete from roles where id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRole, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
delete from sessions where token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteStabilityMetrics = `-- name: DeleteStabilityMetrics :exec
delete from stability_metrics where task_id = $1
`

func (q *Queries) DeleteStabilityMetrics(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStabilityMetrics, taskID)
	return err
}

const deleteStabilitySamples = `-- name: DeleteStabilitySamples :exec
delete from stability_samples where task_id = $1
`

// 重试幂等：清掉上次中断留下的半截时序，整个任务从头重跑
func (q *Queries) DeleteStabilitySamples(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStabilitySamples, taskID)
	return err
}

const deleteTaskCaseResults = `-- name: DeleteTaskCaseResults :exec
delete from task_case_results where task_id = $1
`

func (q *Queries) DeleteTaskCaseResults(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTaskCaseResults, taskID)
	return err
}

const deleteUser = `-- name: DeleteUser :execrows
delete from users where id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
delete from sessions where user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const failOrphanTasks = `-- name: FailOrphanTasks :execrows
update tasks set status = 'failed', error = $1, finished_at = now()
where status = 'running' and id = any ($2::uuid[])
`

type FailOrphanTasksParams struct {
	Error *string
	Ids   []uuid.UUID
}

// 启动孤儿清扫：river_job 已不存在/已终结但任务还挂在 running 的，标记失败
func (q *Queries) FailOrphanTasks(ctx context.Context, arg FailOrphanTasksParams) (int64, error) {
	result, err := q.db.Exec(ctx, failOrphanTasks, arg.Error, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishTask = `-- name: FinishTask :execrows
update tasks set status = $2, error = $3, finished_at = now(),
  progress_done = case when $2 = 'succeeded' then progress_total else progress_done end
where id = $1 and status = 'running'
`

type FinishTaskParams struct {
	ID     uuid.UUID
	Status string
	Error  *string
}

// 终态不可逆：running 之外（已 canceled/failed）不允许再改。
// 成功即进度满：稳定性分母是最坏预估，提前收敛时实发少于分母，不补满进度条会停在半截
func (q *Queries) FinishTask(ctx context.Context, arg FinishTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishTask, arg.ID, arg.Status, arg.Error)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChannel = `-- name: GetChannel :one
select c.id, c.name, c.base_url, c.key_prefix, c.protocols, c.currency, c.note,
       c.disabled, c.last_test, c.probe_interval_minutes, c.probe_model_id, c.created_at,
       (select count(*) from channel_models m where m.channel_id = c.id) as model_count
from channels c
where c.id = $1
`

type GetChannelRow struct {
	ID                   uuid.UUID
	Name                 string
	BaseUrl              string
	KeyPrefix            string
	Protocols            []string
	Currency             string
	Note                 string
	Disabled             bool
	LastTest             []byte
	ProbeIntervalMinutes pgtype.Int4
	ProbeModelID         pgtype.UUID
	CreatedAt            time.Time
	ModelCount           int64
}

func (q *Queries) GetChannel(ctx context.Context, id uuid.UUID) (GetChannelRow, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i GetChannelRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.KeyPrefix,
		&i.Protocols,
		&i.Currency,
		&i.Note,
		&i.Disabled,
		&i.LastTest,
		&i.ProbeIntervalMinutes,
		&i.ProbeModelID,
		&i.CreatedAt,
		&i.ModelCount,
	)
	return i, err
}

const getChannelModel = `-- name: GetChannelModel :one
select id, name, input_price, output_price, cached_input_price, created_at
from channel_models
where id = $1 and channel_id = $2
`

type GetChannelModelParams struct {
	ID        uuid.UUID
	ChannelID uuid.UUID
}

type GetChannelModelRow struct {
	ID               uuid.UUID
	Name             string
	InputPrice       *float64
	OutputPrice      *float64
	CachedInputPrice *float64
	CreatedAt        time.Time
}

func (q *Queries) GetChannelModel(ctx context.Context, arg GetChannelModelParams) (GetChannelModelRow, error) {
	row := q.db.QueryRow(ctx, getChannelModel, arg.ID, arg.ChannelID)
	var i GetChannelModelRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InputPrice,
		&i.OutputPrice,
		&i.CachedInputPrice,
		&i.CreatedAt,
	)
	return i, err
}

const getChannelSecret = `-- name: GetChannelSecret :one
select id, base_url, api_key, protocols from channels where id = $1
`

type GetChannelSecretRow struct {
	ID        uuid.UUID
	BaseUrl   string
	ApiKey    string
	Protocols []string
}

// 连通测试专用：整个代码库唯一读取 api_key 明文的查询，结果绝不进任何响应体
func (q *Queries) GetChannelSecret(ctx context.Context, id uuid.UUID) (GetChannelSecretRow, error) {
	row := q.db.QueryRow(ctx, getChannelSecret, id)
	var i GetChannelSecretRow
	err := row.Scan(
		&i.ID,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Protocols,
	)
	return i, err
}

const getRole = `-- name: GetRole :one
select id, name, built_in, permissions from roles where id = $1
`

type GetRoleRow struct {
	ID          uuid.UUID
	Name        string
	BuiltIn     bool
	Permissions []byte
}

func (q *Queries) GetRole(ctx context.Context, id uuid.UUID) (GetRoleRow, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i GetRoleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BuiltIn,
		&i.Permissions,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
select id, name, built_in, permissions from roles where name = $1
`

type GetRoleByNameRow struct {
	ID          uuid.UUID
	Name        string
	BuiltIn     bool
	Permissions []byte
}

func (q *Queries) GetRoleByName(ctx context.Context, name string) (GetRoleByNameRow, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i GetRoleByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BuiltIn,
		&i.Permissions,
	)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
select u.id, u.username, u.display_name, u.avatar_url, r.name as role_name, r.permissions
from sessions s
join users u on u.id = s.user_id
join roles r on r.id = u.role_id
where s.token_hash = $1 and s.expires_at > now()
`

type GetSessionUserRow struct {
	ID          uuid.UUID
	Username    string
	DisplayName *string
	AvatarUrl   *string
	RoleName    string
	Permissions []byte
}

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash []byte) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i GetSessionUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.RoleName,
		&i.Permissions,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
select t.id, t.kind, t.status, t.channel_id, t.target, t.probes, t.params,
       t.progress_total, t.progress_done, t.error, t.created_at, t.started_at, t.finished_at,
       t.river_job_id,
       u.username as created_by_name
from tasks t
left join users u on u.id = t.created_by
where t.id = $1
`

type GetTaskRow struct {
	ID            uuid.UUID
	Kind          string
	Status        string
	ChannelID     pgtype.UUID
	Target        []byte
	Probes        []string
	Params        []byte
	ProgressTotal int32
	ProgressDone  int32
	Error         *string
	CreatedAt     time.Time
	StartedAt     pgtype.Timestamptz
	FinishedAt    pgtype.Timestamptz
	RiverJobID    pgtype.Int8
	CreatedByName *string
}

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (GetTaskRow, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i GetTaskRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.ChannelID,
		&i.Target,
		&i.Probes,
		&i.Params,
		&i.ProgressTotal,
		&i.ProgressDone,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.RiverJobID,
		&i.CreatedByName,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
select u.id, u.username, u.role_id, r.name as role_name,
       (u.feishu_union_id is not null)::bool as from_feishu, u.created_at
from users u
join roles r on r.id = u.role_id
where u.id = $1
`

type GetUserRow struct {
	ID         uuid.UUID
	Username   string
	RoleID     uuid.UUID
	RoleName   string
	FromFeishu bool
	CreatedAt  time.Time
}

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.RoleID,
		&i.RoleName,
		&i.FromFeishu,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByFeishuUnionID = `-- name: GetUserByFeishuUnionID :one
select u.id from users u where u.feishu_union_id = $1
`

func (q *Queries) GetUserByFeishuUnionID(ctx context.Context, feishuUnionID *string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserByFeishuUnionID, feishuUnionID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
select u.id, u.username, u.password_hash
from users u
where u.username = $1
`

type GetUserByUsernameRow struct {
	ID           uuid.UUID
	Username     string
	PasswordHash *string
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(&i.ID, &i.Username, &i.PasswordHash)
	return i, err
}

const getUserPasswordHash = `-- name: GetUserPasswordHash :one
select password_hash from users where id = $1
`

func (q *Queries) GetUserPasswordHash(ctx context.Context, id uuid.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, getUserPasswordHash, id)
	var password_hash *string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const insertConnectivityResult = `-- name: InsertConnectivityResult :exec
insert into connectivity_results
    (channel_id, model, source, protocol, ok, http_status, ttft_ms, error, tested_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertConnectivityResultParams struct {
	ChannelID  uuid.UUID
	Model      string
	Source     string
	Protocol   string
	Ok         bool
	HttpStatus pgtype.Int4
	TtftMs     pgtype.Int4
	Error      *string
	TestedAt   time.Time
}

func (q *Queries) InsertConnectivityResult(ctx context.Context, arg InsertConnectivityResultParams) error {
	_, err := q.db.Exec(ctx, insertConnectivityResult,
		arg.ChannelID,
		arg.Model,
		arg.Source,
		arg.Protocol,
		arg.Ok,
		arg.HttpStatus,
		arg.TtftMs,
		arg.Error,
		arg.TestedAt,
	)
	return err
}

const insertStabilitySample = `-- name: InsertStabilitySample :exec
insert into stability_samples
    (task_id, probe, stage, stage_index, seq, protocol, dispatched_at,
     ttfb_ms, ttfd_ms, ttft_ms, total_ms, ok, http_status, http_proto, error_class, error,
     input_tokens, output_tokens, cached_tokens, warmup, target_input_tokens, target_output_tokens, reasoning_tokens)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23)
`

type InsertStabilitySampleParams struct {
	TaskID             uuid.UUID
	Probe              string
	Stage              string
	StageIndex         int32
	Seq                int32
	Protocol           string
	DispatchedAt       time.Time
	TtfbMs             pgtype.Int4
	TtfdMs             pgtype.Int4
	TtftMs             pgtype.Int4
	TotalMs            pgtype.Int4
	Ok                 bool
	HttpStatus         pgtype.Int4
	HttpProto          *string
	ErrorClass         *string
	Error              *string
	InputTokens        pgtype.Int4
	OutputTokens       pgtype.Int4
	CachedTokens       pgtype.Int4
	Warmup             bool
	TargetInputTokens  pgtype.Int4
	TargetOutputTokens pgtype.Int4
	ReasoningTokens    pgtype.Int4
}

func (q *Queries) InsertStabilitySample(ctx context.Context, arg InsertStabilitySampleParams) error {
	_, err := q.db.Exec(ctx, insertStabilitySample,
		arg.TaskID,
		arg.Probe,
		arg.Stage,
		arg.StageIndex,
		arg.Seq,
		arg.Protocol,
		arg.DispatchedAt,
		arg.TtfbMs,
		arg.TtfdMs,
		arg.TtftMs,
		arg.TotalMs,
		arg.Ok,
		arg.HttpStatus,
		arg.HttpProto,
		arg.ErrorClass,
		arg.Error,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CachedTokens,
		arg.Warmup,
		arg.TargetInputTokens,
		arg.TargetOutputTokens,
		arg.ReasoningTokens,
	)
	return err
}

const listChannelModels = `-- name: ListChannelModels :many
select id, name, input_price, output_price, cached_input_price, created_at
from channel_models
where channel_id = $1
order by created_at
`

type ListChannelModelsRow struct {
	ID               uuid.UUID
	Name             string
	InputPrice       *float64
	OutputPrice      *float64
	CachedInputPrice *float64
	CreatedAt        time.Time
}

func (q *Queries) ListChannelModels(ctx context.Context, channelID uuid.UUID) ([]ListChannelModelsRow, error) {
	rows, err := q.db.Query(ctx, listChannelModels, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelModelsRow
	for rows.Next() {
		var i ListChannelModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InputPrice,
			&i.OutputPrice,
			&i.CachedInputPrice,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannels = `-- name: ListChannels :many
select c.id, c.name, c.base_url, c.key_prefix, c.protocols, c.currency, c.note,
       c.disabled, c.last_test, c.probe_interval_minutes, c.probe_model_id, c.created_at,
       (select count(*) from channel_models m where m.channel_id = c.id) as model_count
from channels c
order by c.created_at
`

type ListChannelsRow struct {
	ID                   uuid.UUID
	Name                 string
	BaseUrl              string
	KeyPrefix            string
	Protocols            []string
	Currency             string
	Note                 string
	Disabled             bool
	LastTest             []byte
	ProbeIntervalMinutes pgtype.Int4
	ProbeModelID         pgtype.UUID
	CreatedAt            time.Time
	ModelCount           int64
}

func (q *Queries) ListChannels(ctx context.Context) ([]ListChannelsRow, error) {
	rows, err := q.db.Query(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelsRow
	for rows.Next() {
		var i ListChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.KeyPrefix,
			&i.Protocols,
			&i.Currency,
			&i.Note,
			&i.Disabled,
			&i.LastTest,
			&i.ProbeIntervalMinutes,
			&i.ProbeModelID,
			&i.CreatedAt,
			&i.ModelCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectivityHistory = `-- name: ListConnectivityHistory :many
select model, source, protocol, ok, http_status, ttft_ms, error, tested_at
from connectivity_results
where channel_id = $1
  and tested_at >= now() - make_interval(hours => $2::int)
order by tested_at
`

type ListConnectivityHistoryParams struct {
	ChannelID uuid.UUID
	Hours     int32
}

type ListConnectivityHistoryRow struct {
	Model      string
	Source     string
	Protocol   string
	Ok         bool
	HttpStatus pgtype.Int4
	TtftMs     pgtype.Int4
	Error      *string
	TestedAt   time.Time
}

func (q *Queries) ListConnectivityHistory(ctx context.Context, arg ListConnectivityHistoryParams) ([]ListConnectivityHistoryRow, error) {
	rows, err := q.db.Query(ctx, listConnectivityHistory, arg.ChannelID, arg.Hours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConnectivityHistoryRow
	for rows.Next() {
		var i ListConnectivityHistoryRow
		if err := rows.Scan(
			&i.Model,
			&i.Source,
			&i.Protocol,
			&i.Ok,
			&i.HttpStatus,
			&i.TtftMs,
			&i.Error,
			&i.TestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueProbeChannels = `-- name: ListDueProbeChannels :many
select c.id, m.name as model_name
from channels c
join channel_models m on m.id = c.probe_model_id
where c.probe_interval_minutes is not null
  and not c.disabled
  and coalesce(
        (select max(r.tested_at) from connectivity_results r
         where r.channel_id = c.id and r.source = 'scheduled'),
        '-infinity'::timestamptz
      ) <= now() - make_interval(mins => c.probe_interval_minutes)
`

type ListDueProbeChannelsRow struct {
	ID        uuid.UUID
	ModelName string
}

// 定时探活到期渠道：已配置间隔 + 未停用 + 探活模型仍在（被删则 join 不到自动停摆）；
// 节奏只看最近一次 scheduled 探测（手动测试不重置定时），从未跑过视为立即到期
func (q *Queries) ListDueProbeChannels(ctx context.Context) ([]ListDueProbeChannelsRow, error) {
	rows, err := q.db.Query(ctx, listDueProbeChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueProbeChannelsRow
	for rows.Next() {
		var i ListDueProbeChannelsRow
		if err := rows.Scan(&i.ID, &i.ModelName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestTerminalQualityTasks = `-- name: ListLatestTerminalQualityTasks :many
select distinct on (t.channel_id, t.target->>'model')
    t.id, t.channel_id, t.status, t.target, t.probes, t.finished_at
from tasks t
where t.kind = 'quality'
  and t.channel_id is not null
  and t.status in ('succeeded', 'failed', 'canceled')
order by t.channel_id, t.target->>'model', t.created_at desc
`

type ListLatestTerminalQualityTasksRow struct {
	ID         uuid.UUID
	ChannelID  pgtype.UUID
	Status     string
	Target     []byte
	Probes     []string
	FinishedAt pgtype.Timestamptz
}

// 总览评分：每个 渠道 × 模型名快照 取最近一个终态质量任务；
// 按 target->>'model' 名快照分组（老任务快照无 modelEntryId），与 connectivity_results.model 口径一致
func (q *Queries) ListLatestTerminalQualityTasks(ctx context.Context) ([]ListLatestTerminalQualityTasksRow, error) {
	rows, err := q.db.Query(ctx, listLatestTerminalQualityTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestTerminalQualityTasksRow
	for rows.Next() {
		var i ListLatestTerminalQualityTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Status,
			&i.Target,
			&i.Probes,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
select id, name, built_in, permissions from roles order by created_at
`

type ListRolesRow struct {
	ID          uuid.UUID
	Name        string
	BuiltIn     bool
	Permissions []byte
}

func (q *Queries) ListRoles(ctx context.Context) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolesRow
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BuiltIn,
			&i.Permissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningTasks = `-- name: ListRunningTasks :many
select id, river_job_id from tasks where status = 'running'
`

type ListRunningTasksRow struct {
	ID         uuid.UUID
	RiverJobID pgtype.Int8
}

func (q *Queries) ListRunningTasks(ctx context.Context) ([]ListRunningTasksRow, error) {
	rows, err := q.db.Query(ctx, listRunningTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunningTasksRow
	for rows.Next() {
		var i ListRunningTasksRow
		if err := rows.Scan(&i.ID, &i.RiverJobID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStabilityMetrics = `-- name: ListStabilityMetrics :many
select probe, stage, stage_index, metrics, created_at
from stability_metrics
where task_id = $1
order by probe, stage_index
`

type ListStabilityMetricsRow struct {
	Probe      string
	Stage      string
	StageIndex int32
	Metrics    []byte
	CreatedAt  time.Time
}

// 详情/导出：按 probe、档序取回全部聚合点（__overall__ 的 stage_index=-1 排最后）
func (q *Queries) ListStabilityMetrics(ctx context.Context, taskID uuid.UUID) ([]ListStabilityMetricsRow, error) {
	rows, err := q.db.Query(ctx, listStabilityMetrics, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStabilityMetricsRow
	for rows.Next() {
		var i ListStabilityMetricsRow
		if err := rows.Scan(
			&i.Probe,
			&i.Stage,
			&i.StageIndex,
			&i.Metrics,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStabilitySamples = `-- name: ListStabilitySamples :many
select probe, stage, stage_index, seq, protocol, dispatched_at,
       ttfb_ms, ttfd_ms, ttft_ms, total_ms, ok, http_status, http_proto, error_class, error,
       input_tokens, output_tokens, cached_tokens, warmup, target_input_tokens, target_output_tokens, reasoning_tokens
from stability_samples
where task_id = $1
order by probe, stage_index, seq
`

type ListStabilitySamplesRow struct {
	Probe              string
	Stage              string
	StageIndex         int32
	Seq                int32
	Protocol           string
	DispatchedAt       time.Time
	TtfbMs             pgtype.Int4
	TtfdMs             pgtype.Int4
	TtftMs             pgtype.Int4
	TotalMs            pgtype.Int4
	Ok                 bool
	HttpStatus         pgtype.Int4
	HttpProto          *string
	ErrorClass         *string
	Error              *string
	InputTokens        pgtype.Int4
	OutputTokens       pgtype.Int4
	CachedTokens       pgtype.Int4
	Warmup             bool
	TargetInputTokens  pgtype.Int4
	TargetOutputTokens pgtype.Int4
	ReasoningTokens    pgtype.Int4
}

// 导出证据链：全量逐请求时序
func (q *Queries) ListStabilitySamples(ctx context.Context, taskID uuid.UUID) ([]ListStabilitySamplesRow, error) {
	rows, err := q.db.Query(ctx, listStabilitySamples, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStabilitySamplesRow
	for rows.Next() {
		var i ListStabilitySamplesRow
		if err := rows.Scan(
			&i.Probe,
			&i.Stage,
			&i.StageIndex,
			&i.Seq,
			&i.Protocol,
			&i.DispatchedAt,
			&i.TtfbMs,
			&i.TtfdMs,
			&i.TtftMs,
			&i.TotalMs,
			&i.Ok,
			&i.HttpStatus,
			&i.HttpProto,
			&i.ErrorClass,
			&i.Error,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedTokens,
			&i.Warmup,
			&i.TargetInputTokens,
			&i.TargetOutputTokens,
			&i.ReasoningTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskCaseResults = `-- name: ListTaskCaseResults :many
select probe, suite, line, mode, selection_reason, status, message,
       http_status, latency_ms, arguments, attempts
from task_case_results
where task_id = $1
  and ($2::text is null or status = $2::text)
order by probe, suite, line, mode
`

type ListTaskCaseResultsParams struct {
	TaskID uuid.UUID
	Status *string
}

type ListTaskCaseResultsRow struct {
	Probe           string
	Suite           string
	Line            int32
	Mode            string
	SelectionReason string
	Status          string
	Message         string
	HttpStatus      pgtype.Int4
	LatencyMs       pgtype.Int4
	Arguments       *string
	Attempts        int32
}

func (q *Queries) ListTaskCaseResults(ctx context.Context, arg ListTaskCaseResultsParams) ([]ListTaskCaseResultsRow, error) {
	rows, err := q.db.Query(ctx, listTaskCaseResults, arg.TaskID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskCaseResultsRow
	for rows.Next() {
		var i ListTaskCaseResultsRow
		if err := rows.Scan(
			&i.Probe,
			&i.Suite,
			&i.Line,
			&i.Mode,
			&i.SelectionReason,
			&i.Status,
			&i.Message,
			&i.HttpStatus,
			&i.LatencyMs,
			&i.Arguments,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
select t.id, t.kind, t.status, t.channel_id, t.target, t.probes, t.params,
       t.progress_total, t.progress_done, t.error, t.created_at, t.started_at, t.finished_at,
       t.river_job_id,
       u.username as created_by_name
from tasks t
left join users u on u.id = t.created_by
where t.kind = $1
  and ($4::text is null or t.status = $4::text)
  and ($5::uuid is null or t.channel_id = $5::uuid)
order by t.created_at desc
limit $2 offset $3
`

type ListTasksParams struct {
	Kind      string
	Limit     int32
	Offset    int32
	Status    *string
	ChannelID pgtype.UUID
}

type ListTasksRow struct {
	ID            uuid.UUID
	Kind          string
	Status        string
	ChannelID     pgtype.UUID
	Target        []byte
	Probes        []string
	Params        []byte
	ProgressTotal int32
	ProgressDone  int32
	Error         *string
	CreatedAt     time.Time
	StartedAt     pgtype.Timestamptz
	FinishedAt    pgtype.Timestamptz
	RiverJobID    pgtype.Int8
	CreatedByName *string
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.Kind,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.ChannelID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksRow
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.ChannelID,
			&i.Target,
			&i.Probes,
			&i.Params,
			&i.ProgressTotal,
			&i.ProgressDone,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.RiverJobID,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
select u.id, u.username, u.role_id, r.name as role_name,
       (u.feishu_union_id is not null)::bool as from_feishu, u.created_at
from users u
join roles r on r.id = u.role_id
order by u.created_at
`

type ListUsersRow struct {
	ID         uuid.UUID
	Username   string
	RoleID     uuid.UUID
	RoleName   string
	FromFeishu bool
	CreatedAt  time.Time
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.RoleID,
			&i.RoleName,
			&i.FromFeishu,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskRunning = `-- name: MarkTaskRunning :execrows
update tasks set status = 'running', started_at = coalesce(started_at, now())
where id = $1 and status in ('queued', 'running')
`

// 状态守卫：只允许 queued→running（River 重试进来时若已是终态则不重置）
func (q *Queries) MarkTaskRunning(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markTaskRunning, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const refreshFeishuUserProfile = `-- name: RefreshFeishuUserProfile :exec
update users set feishu_open_id = $2, display_name = $3, avatar_url = $4 where id = $1
`

type RefreshFeishuUserProfileParams struct {
	ID           uuid.UUID
	FeishuOpenID *string
	DisplayName  *string
	AvatarUrl    *string
}

func (q *Queries) RefreshFeishuUserProfile(ctx context.Context, arg RefreshFeishuUserProfileParams) error {
	_, err := q.db.Exec(ctx, refreshFeishuUserProfile,
		arg.ID,
		arg.FeishuOpenID,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	return err
}

const setTaskRiverJobID = `-- name: SetTaskRiverJobID :exec
update tasks set river_job_id = $2 where id = $1
`

type SetTaskRiverJobIDParams struct {
	ID         uuid.UUID
	RiverJobID pgtype.Int8
}

func (q *Queries) SetTaskRiverJobID(ctx context.Context, arg SetTaskRiverJobIDParams) error {
	_, err := q.db.Exec(ctx, setTaskRiverJobID, arg.ID, arg.RiverJobID)
	return err
}

const updateChannel = `-- name: UpdateChannel :execrows
update channels set
    name       = coalesce($1, name),
    base_url   = coalesce($2, base_url),
    api_key    = coalesce($3, api_key),
    key_prefix = coalesce($4, key_prefix),
    protocols  = coalesce($5, protocols),
    currency   = coalesce($6, currency),
    note       = coalesce($7, note),
    disabled   = coalesce($8, disabled)
where id = $9
`

type UpdateChannelParams struct {
	Name      *string
	BaseUrl   *string
	ApiKey    *string
	KeyPrefix *string
	Protocols []string
	Currency  *string
	Note      *string
	Disabled  *bool
	ID        uuid.UUID
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateChannel,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKey,
		arg.KeyPrefix,
		arg.Protocols,
		arg.Currency,
		arg.Note,
		arg.Disabled,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateChannelLastTest = `-- name: UpdateChannelLastTest :execrows
update channels set last_test = $2 where id = $1
`

type UpdateChannelLastTestParams struct {
	ID       uuid.UUID
	LastTest []byte
}

func (q *Queries) UpdateChannelLastTest(ctx context.Context, arg UpdateChannelLastTestParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateChannelLastTest, arg.ID, arg.LastTest)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateChannelModel = `-- name: UpdateChannelModel :one
update channel_models
set name = $3, input_price = $4, output_price = $5, cached_input_price = $6
where id = $1 and channel_id = $2
returning id, name, input_price, output_price, cached_input_price, created_at
`

type UpdateChannelModelParams struct {
	ID               uuid.UUID
	ChannelID        uuid.UUID
	Name             string
	InputPrice       *float64
	OutputPrice      *float64
	CachedInputPrice *float64
}

type UpdateChannelModelRow struct {
	ID               uuid.UUID
	Name             string
	InputPrice       *float64
	OutputPrice      *float64
	CachedInputPrice *float64
	CreatedAt        time.Time
}

func (q *Queries) UpdateChannelModel(ctx context.Context, arg UpdateChannelModelParams) (UpdateChannelModelRow, error) {
	row := q.db.QueryRow(ctx, updateChannelModel,
		arg.ID,
		arg.ChannelID,
		arg.Name,
		arg.InputPrice,
		arg.OutputPrice,
		arg.CachedInputPrice,
	)
	var i UpdateChannelModelRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InputPrice,
		&i.OutputPrice,
		&i.CachedInputPrice,
		&i.CreatedAt,
	)
	return i, err
}

const updateChannelProbeConfig = `-- name: UpdateChannelProbeConfig :execrows
update channels set probe_interval_minutes = $2, probe_model_id = $3 where id = $1
`

type UpdateChannelProbeConfigParams struct {
	ID                   uuid.UUID
	ProbeIntervalMinutes pgtype.Int4
	ProbeModelID         pgtype.UUID
}

// 探活配置成对整体覆盖（可写 null = 关闭）：UpdateChannel 的 coalesce(narg) 写不了 null，故专设
func (q *Queries) UpdateChannelProbeConfig(ctx context.Context, arg UpdateChannelProbeConfigParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateChannelProbeConfig, arg.ID, arg.ProbeIntervalMinutes, arg.ProbeModelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRole = `-- name: UpdateRole :one
update roles set name = $2, permissions = $3
where id = $1
returning id, name, built_in, permissions
`

type UpdateRoleParams struct {
	ID          uuid.UUID
	Name        string
	Permissions []byte
}

type UpdateRoleRow struct {
	ID          uuid.UUID
	Name        string
	BuiltIn     bool
	Permissions []byte
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (UpdateRoleRow, error) {
	row := q.db.QueryRow(ctx, updateRole, arg.ID, arg.Name, arg.Permissions)
	var i UpdateRoleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BuiltIn,
		&i.Permissions,
	)
	return i, err
}

const updateTaskProgress = `-- name: UpdateTaskProgress :exec
update tasks set progress_total = $2, progress_done = $3
where id = $1 and status = 'running'
`

type UpdateTaskProgressParams struct {
	ID            uuid.UUID
	ProgressTotal int32
	ProgressDone  int32
}

// 守卫 running：任务被取消后 worker 残余的进度写入不再污染定格记录
func (q *Queries) UpdateTaskProgress(ctx context.Context, arg UpdateTaskProgressParams) error {
	_, err := q.db.Exec(ctx, updateTaskProgress, arg.ID, arg.ProgressTotal, arg.ProgressDone)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
update users set password_hash = $2 where id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash *string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserRole = `-- name: UpdateUserRole :execrows
update users set role_id = $2 where id = $1
`

type UpdateUserRoleParams struct {
	ID     uuid.UUID
	RoleID uuid.UUID
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserRole, arg.ID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertFeishuUser = `-- name: UpsertFeishuUser :one
insert into users (username, password_hash, role_id, feishu_union_id, feishu_open_id, display_name, avatar_url)
values ($1, null, $2, $3, $4, $5, $6)
on conflict (feishu_union_id) do update
   set feishu_open_id = excluded.feishu_open_id,
       display_name   = excluded.display_name,
       avatar_url     = excluded.avatar_url
returning id
`

type UpsertFeishuUserParams struct {
	Username      string
	RoleID        uuid.UUID
	FeishuUnionID *string
	FeishuOpenID  *string
	DisplayName   *string
	AvatarUrl     *string
}

// 首次登录自动建号；并发下同一 union_id 只会落一行，冲突分支只刷新资料（用户名保持原样）
func (q *Queries) UpsertFeishuUser(ctx context.Context, arg UpsertFeishuUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertFeishuUser,
		arg.Username,
		arg.RoleID,
		arg.FeishuUnionID,
		arg.FeishuOpenID,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertStabilityMetric = `-- name: UpsertStabilityMetric :exec
insert into stability_metrics (task_id, probe, stage, stage_index, metrics)
values ($1, $2, $3, $4, $5)
on conflict (task_id, probe, stage) do update set
    stage_index = excluded.stage_index,
    metrics     = excluded.metrics,
    created_at  = now()
`

type UpsertStabilityMetricParams struct {
	TaskID     uuid.UUID
	Probe      string
	Stage      string
	StageIndex int32
	Metrics    []byte
}

// 评估期聚合点落库（同任务重跑幂等覆盖）
func (q *Queries) UpsertStabilityMetric(ctx context.Context, arg UpsertStabilityMetricParams) error {
	_, err := q.db.Exec(ctx, upsertStabilityMetric,
		arg.TaskID,
		arg.Probe,
		arg.Stage,
		arg.StageIndex,
		arg.Metrics,
	)
	return err
}

const upsertTaskCaseResult = `-- name: UpsertTaskCaseResult :exec
insert into task_case_results
    (task_id, probe, suite, line, mode, selection_reason, status, message,
     http_status, latency_ms, arguments, attempts)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
on conflict (task_id, probe, suite, line, mode) do update set
    selection_reason = excluded.selection_reason,
    status           = excluded.status,
    message          = excluded.message,
    http_status      = excluded.http_status,
    latency_ms       = excluded.latency_ms,
    arguments        = excluded.arguments,
    attempts         = excluded.attempts
`

type UpsertTaskCaseResultParams struct {
	TaskID          uuid.UUID
	Probe           string
	Suite           string
	Line            int32
	Mode            string
	SelectionReason string
	Status          string
	Message         string
	HttpStatus      pgtype.Int4
	LatencyMs       pgtype.Int4
	Arguments       *string
	Attempts        int32
}

func (q *Queries) UpsertTaskCaseResult(ctx context.Context, arg UpsertTaskCaseResultParams) error {
	_, err := q.db.Exec(ctx, upsertTaskCaseResult,
		arg.TaskID,
		arg.Probe,
		arg.Suite,
		arg.Line,
		arg.Mode,
		arg.SelectionReason,
		arg.Status,
		arg.Message,
		arg.HttpStatus,
		arg.LatencyMs,
		arg.Arguments,
		arg.Attempts,
	)
	return err
}

const usernameExists = `-- name: UsernameExists :one
select exists (select 1 from users where username = $1)
`

func (q *Queries) UsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, usernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
