//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuthSource.
const (
	Feishu   AuthSource = "feishu"
	Password AuthSource = "password"
)

// Valid indicates whether the value is a known member of the AuthSource enum.
func (e AuthSource) Valid() bool {
	switch e {
	case Feishu:
		return true
	case Password:
		return true
	default:
		return false
	}
}

// Defines values for CaseMode.
const (
	NonStream CaseMode = "non_stream"
	Stream    CaseMode = "stream"
)

// Valid indicates whether the value is a known member of the CaseMode enum.
func (e CaseMode) Valid() bool {
	switch e {
	case NonStream:
		return true
	case Stream:
		return true
	default:
		return false
	}
}

// Defines values for CaseStatus.
const (
	Collected CaseStatus = "collected"
	Passed    CaseStatus = "passed"
	Rejected  CaseStatus = "rejected"
	Violated  CaseStatus = "violated"
)

// Valid indicates whether the value is a known member of the CaseStatus enum.
func (e CaseStatus) Valid() bool {
	switch e {
	case Collected:
		return true
	case Passed:
		return true
	case Rejected:
		return true
	case Violated:
		return true
	default:
		return false
	}
}

// Defines values for ConnectivitySource.
const (
	Manual    ConnectivitySource = "manual"
	Scheduled ConnectivitySource = "scheduled"
)

// Valid indicates whether the value is a known member of the ConnectivitySource enum.
func (e ConnectivitySource) Valid() bool {
	switch e {
	case Manual:
		return true
	case Scheduled:
		return true
	default:
		return false
	}
}

// Defines values for Currency.
const (
	CNY Currency = "CNY"
	USD Currency = "USD"
)

// Valid indicates whether the value is a known member of the Currency enum.
func (e Currency) Valid() bool {
	switch e {
	case CNY:
		return true
	case USD:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for Protocol.
const (
	AnthropicMessages Protocol = "anthropic_messages"
	OpenaiChat        Protocol = "openai_chat"
	OpenaiResponses   Protocol = "openai_responses"
)

// Valid indicates whether the value is a known member of the Protocol enum.
func (e Protocol) Valid() bool {
	switch e {
	case AnthropicMessages:
		return true
	case OpenaiChat:
		return true
	case OpenaiResponses:
		return true
	default:
		return false
	}
}

// Defines values for StabilityMetricsTruncatedBy.
const (
	Duration StabilityMetricsTruncatedBy = "duration"
	Requests StabilityMetricsTruncatedBy = "requests"
	Tokens   StabilityMetricsTruncatedBy = "tokens"
)

// Valid indicates whether the value is a known member of the StabilityMetricsTruncatedBy enum.
func (e StabilityMetricsTruncatedBy) Valid() bool {
	switch e {
	case Duration:
		return true
	case Requests:
		return true
	case Tokens:
		return true
	default:
		return false
	}
}

// Defines values for StabilityWorkloadInputMode.
const (
	Fixed  StabilityWorkloadInputMode = "fixed"
	Jitter StabilityWorkloadInputMode = "jitter"
	None   StabilityWorkloadInputMode = "none"
	Ramp   StabilityWorkloadInputMode = "ramp"
)

// Valid indicates whether the value is a known member of the StabilityWorkloadInputMode enum.
func (e StabilityWorkloadInputMode) Valid() bool {
	switch e {
	case Fixed:
		return true
	case Jitter:
		return true
	case None:
		return true
	case Ramp:
		return true
	default:
		return false
	}
}

// Defines values for TaskStatus.
const (
	Canceled  TaskStatus = "canceled"
	Failed    TaskStatus = "failed"
	Queued    TaskStatus = "queued"
	Running   TaskStatus = "running"
	Succeeded TaskStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the TaskStatus enum.
func (e TaskStatus) Valid() bool {
	switch e {
	case Canceled:
		return true
	case Failed:
		return true
	case Queued:
		return true
	case Running:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// Defines values for ExportQualityTaskParamsFormat.
const (
	ExportQualityTaskParamsFormatJson  ExportQualityTaskParamsFormat = "json"
	ExportQualityTaskParamsFormatJunit ExportQualityTaskParamsFormat = "junit"
)

// Valid indicates whether the value is a known member of the ExportQualityTaskParamsFormat enum.
func (e ExportQualityTaskParamsFormat) Valid() bool {
	switch e {
	case ExportQualityTaskParamsFormatJson:
		return true
	case ExportQualityTaskParamsFormatJunit:
		return true
	default:
		return false
	}
}

// Defines values for ExportStabilityTaskParamsFormat.
const (
	ExportStabilityTaskParamsFormatJson ExportStabilityTaskParamsFormat = "json"
)

// Valid indicates whether the value is a known member of the ExportStabilityTaskParamsFormat enum.
func (e ExportStabilityTaskParamsFormat) Valid() bool {
	switch e {
	case ExportStabilityTaskParamsFormatJson:
		return true
	default:
		return false
	}
}

// AuthMethods 登录页据此决定渲染哪些入口
type AuthMethods struct {
	// Feishu 是否已配置飞书 OAuth 登录
	Feishu bool `json:"feishu"`

	// Password 是否保留用户名密码登录（管理员兜底通道）
	Password bool `json:"password"`
}

// AuthSource defines model for AuthSource.
type AuthSource string

// CaseMode defines model for CaseMode.
type CaseMode string

// CaseStatus 用例判定：rejected=请求被上游拒绝（HTTP/传输错误）；violated=响应到手但不合规；passed=合规；collected=已采集·待评估（跨行断言检测项运行中的中间态，只含原始计数不含结论，任务结束后必被终态覆盖）
type CaseStatus string

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
}

// Channel defines model for Channel.
type Channel struct {
	// BaseUrl 填到版本段（如 https://api.example.com/v1），平台按协议拼固定末段
	BaseUrl   string    `json:"baseUrl"`
	CreatedAt time.Time `json:"createdAt"`

	// Currency 渠道定价币种（仅标注，不做汇率换算）
	Currency Currency `json:"currency"`

	// Disabled 停用后不可选入新检测任务，配置与 key 保留
	Disabled bool               `json:"disabled"`
	Id       openapi_types.UUID `json:"id"`

	// KeyPrefix API key 脱敏前缀（key 写后不可回读）
	KeyPrefix  string            `json:"keyPrefix"`
	LastTest   *ConnectivityTest `json:"lastTest,omitempty"`
	ModelCount int               `json:"modelCount"`
	Name       string            `json:"name"`
	Note       string            `json:"note"`

	// ProbeIntervalMinutes 定时探活间隔分钟（1-1440）；缺省=未开启
	ProbeIntervalMinutes *int `json:"probeIntervalMinutes,omitempty"`

	// ProbeModelId 定时探活用的模型条目；条目被删自动置空、调度停摆
	ProbeModelId *openapi_types.UUID `json:"probeModelId,omitempty"`
	Protocols    []Protocol          `json:"protocols"`
}

// ChannelCreate defines model for ChannelCreate.
type ChannelCreate struct {
	ApiKey string `json:"apiKey"`

	// BaseUrl 填到版本段（如 https://api.example.com/v1），末尾斜杠会被自动去除
	BaseUrl string `json:"baseUrl"`

	// Currency 渠道定价币种（仅标注，不做汇率换算）
	Currency  *Currency  `json:"currency,omitempty"`
	Name      string     `json:"name"`
	Note      *string    `json:"note,omitempty"`
	Protocols []Protocol `json:"protocols"`
}

// ChannelDetail defines model for ChannelDetail.
type ChannelDetail struct {
	// BaseUrl 填到版本段（如 https://api.example.com/v1），平台按协议拼固定末段
	BaseUrl   string    `json:"baseUrl"`
	CreatedAt time.Time `json:"createdAt"`

	// Currency 渠道定价币种（仅标注，不做汇率换算）
	Currency Currency `json:"currency"`

	// Disabled 停用后不可选入新检测任务，配置与 key 保留
	Disabled bool               `json:"disabled"`
	Id       openapi_types.UUID `json:"id"`

	// KeyPrefix API key 脱敏前缀（key 写后不可回读）
	KeyPrefix  string            `json:"keyPrefix"`
	LastTest   *ConnectivityTest `json:"lastTest,omitempty"`
	ModelCount int               `json:"modelCount"`
	Models     []ModelEntry      `json:"models"`
	Name       string            `json:"name"`
	Note       string            `json:"note"`

	// ProbeIntervalMinutes 定时探活间隔分钟（1-1440）；缺省=未开启
	ProbeIntervalMinutes *int `json:"probeIntervalMinutes,omitempty"`

	// ProbeModelId 定时探活用的模型条目；条目被删自动置空、调度停摆
	ProbeModelId *openapi_types.UUID `json:"probeModelId,omitempty"`
	Protocols    []Protocol          `json:"protocols"`
}

// ChannelUpdate defines model for ChannelUpdate.
type ChannelUpdate struct {
	// ApiKey 缺省=不改；给值=整体覆盖
	ApiKey  *string `json:"apiKey,omitempty"`
	BaseUrl *string `json:"baseUrl,omitempty"`

	// Currency 渠道定价币种（仅标注，不做汇率换算）
	Currency *Currency `json:"currency,omitempty"`
	Disabled *bool     `json:"disabled,omitempty"`
	Name     *string   `json:"name,omitempty"`
	Note     *string   `json:"note,omitempty"`

	// ProbeIntervalMinutes 定时探活间隔分钟；须与 probeModelId 成对提交整体覆盖，0=关闭（coalesce 语义写不了 null，故用 0 哨兵）
	ProbeIntervalMinutes *int `json:"probeIntervalMinutes,omitempty"`

	// ProbeModelId 定时探活模型条目（须属本渠道）；probeIntervalMinutes=0 时可缺省
	ProbeModelId *openapi_types.UUID `json:"probeModelId,omitempty"`
	Protocols    *[]Protocol         `json:"protocols,omitempty"`
}

// CheckpointScore 一个评分检查点的聚合结果；得分 = passed/total × 100（rejected 与 violated 均计失败）
type CheckpointScore struct {
	// Id 检查点稳定标识（检测项元数据声明）
	Id       string `json:"id"`
	Name     string `json:"name"`
	Passed   int    `json:"passed"`
	Rejected int    `json:"rejected"`

	// Score 0-100；未采样（total=0，如被用例上限截掉）时缺省且不参与加权
	Score    *float32 `json:"score,omitempty"`
	Total    int      `json:"total"`
	Violated int      `json:"violated"`

	// Weight 同一检测项内的相对权重
	Weight float32 `json:"weight"`
}

// ConnectivityHistoryPoint 连通历史点：一行=（一次测试 × 一协议），同次测试各协议行 testedAt 严格一致，前端按其分组还原一次测试
type ConnectivityHistoryPoint struct {
	// Model 当时探测用的模型名快照
	Model string `json:"model"`
	Ok    bool   `json:"ok"`

	// Protocol 渠道支持的接口协议
	Protocol Protocol `json:"protocol"`

	// Source 探测来源：manual=手动测试、scheduled=定时探活
	Source   ConnectivitySource `json:"source"`
	TestedAt time.Time          `json:"testedAt"`

	// TtftMs 首字延迟毫秒；失败时缺省（曲线在此断点留白）
	TtftMs *int `json:"ttftMs,omitempty"`
}

// ConnectivityResult defines model for ConnectivityResult.
type ConnectivityResult struct {
	// Error 失败摘要（超时/连接错误/上游错误体截断）
	Error *string `json:"error,omitempty"`
	Ok    bool    `json:"ok"`

	// Protocol 渠道支持的接口协议
	Protocol Protocol `json:"protocol"`

	// Status 上游 HTTP 状态码（网络层失败时缺省）
	Status *int `json:"status,omitempty"`

	// TtftMs 首字延迟毫秒（流式首个数据帧到达；失败时缺省）
	TtftMs *int `json:"ttftMs,omitempty"`
}

// ConnectivitySource 探测来源：manual=手动测试、scheduled=定时探活
type ConnectivitySource string

// ConnectivityTest defines model for ConnectivityTest.
type ConnectivityTest struct {
	// Model 当时用于探测的模型名（快照，不随模型条目改名变化）
	Model    string               `json:"model"`
	Results  []ConnectivityResult `json:"results"`
	TestedAt time.Time            `json:"testedAt"`
}

// ConnectivityTestRequest defines model for ConnectivityTestRequest.
type ConnectivityTestRequest struct {
	// ModelId 用哪个模型条目发探测请求
	ModelId openapi_types.UUID `json:"modelId"`
}

// Currency 渠道定价币种（仅标注，不做汇率换算）
type Currency string

// CurrentUser defines model for CurrentUser.
type CurrentUser struct {
	// AvatarUrl 飞书头像地址，密码账号为空
	AvatarUrl *string `json:"avatarUrl,omitempty"`

	// DisplayName 飞书账号的姓名，密码账号为空
	DisplayName *string            `json:"displayName,omitempty"`
	Id          openapi_types.UUID `json:"id"`

	// Permissions 粗粒度模块权限开关：控制对应页面与该模块全部接口的访问
	Permissions PermissionMap `json:"permissions"`
	Role        string        `json:"role"`
	Username    string        `json:"username"`
}

// DeployRequest defines model for DeployRequest.
type DeployRequest struct {
	// Tag 要部署的版本 tag（须是已存在的 GitHub Release）
	Tag string `json:"tag"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// ModelEntry defines model for ModelEntry.
type ModelEntry struct {
	CachedInputPrice *float32           `json:"cachedInputPrice,omitempty"`
	CreatedAt        time.Time          `json:"createdAt"`
	Id               openapi_types.UUID `json:"id"`

	// InputPrice 每 1M token 输入单价（币种见渠道）；三个价格字段全缺省=未定价
	InputPrice  *float32 `json:"inputPrice,omitempty"`
	Name        string   `json:"name"`
	OutputPrice *float32 `json:"outputPrice,omitempty"`
}

// ModelEntryUpsert 输入/输出价须成对出现；缓存读价只能在前两者存在时给出（服务端校验）
type ModelEntryUpsert struct {
	CachedInputPrice *float32 `json:"cachedInputPrice,omitempty"`
	InputPrice       *float32 `json:"inputPrice,omitempty"`
	Name             string   `json:"name"`
	OutputPrice      *float32 `json:"outputPrice,omitempty"`
}

// OverviewChannel defines model for OverviewChannel.
type OverviewChannel struct {
	// BaseUrl 填到版本段（如 https://api.example.com/v1），平台按协议拼固定末段
	BaseUrl   string    `json:"baseUrl"`
	CreatedAt time.Time `json:"createdAt"`

	// Currency 渠道定价币种（仅标注，不做汇率换算）
	Currency Currency `json:"currency"`

	// Disabled 停用后不可选入新检测任务，配置与 key 保留
	Disabled bool               `json:"disabled"`
	Id       openapi_types.UUID `json:"id"`

	// KeyPrefix API key 脱敏前缀（key 写后不可回读）
	KeyPrefix  string            `json:"keyPrefix"`
	LastTest   *ConnectivityTest `json:"lastTest,omitempty"`
	ModelCount int               `json:"modelCount"`

	// Models 有终态质量任务的模型得分行（按模型名去重取最近一次）
	Models []OverviewModelScore `json:"models"`
	Name   string               `json:"name"`
	Note   string               `json:"note"`

	// ProbeIntervalMinutes 定时探活间隔分钟（1-1440）；缺省=未开启
	ProbeIntervalMinutes *int `json:"probeIntervalMinutes,omitempty"`

	// ProbeModelId 定时探活用的模型条目；条目被删自动置空、调度停摆
	ProbeModelId *openapi_types.UUID `json:"probeModelId,omitempty"`
	Protocols    []Protocol          `json:"protocols"`
}

// OverviewModelScore 总览卡片单模型得分行：该渠道 × 模型名快照的最近一个终态质量任务即时计算；taskStatus 非 succeeded 时得分基于不完整采样，前端须挂状态标注
type OverviewModelScore struct {
	FinishedAt *time.Time `json:"finishedAt,omitempty"`

	// Model 模型名快照（与任务快照、连通历史同口径）
	Model string `json:"model"`

	// ModelEntryId 任务快照里的模型条目 id（老任务缺省；用于匹配默认探活模型）
	ModelEntryId *openapi_types.UUID `json:"modelEntryId,omitempty"`

	// Score 总分 0-100，口径与任务报告一致；无已采样检查点时缺省
	Score      *float32           `json:"score,omitempty"`
	TaskId     openapi_types.UUID `json:"taskId"`
	TaskStatus TaskStatus         `json:"taskStatus"`
}

// PermissionMap 粗粒度模块权限开关：控制对应页面与该模块全部接口的访问
type PermissionMap struct {
	Channels  bool `json:"channels"`
	Quality   bool `json:"quality"`
	Stability bool `json:"stability"`
	System    bool `json:"system"`
	Users     bool `json:"users"`
}

// ProbeInfo defines model for ProbeInfo.
type ProbeInfo struct {
	// CaseCount 全量用例数
	CaseCount   int    `json:"caseCount"`
	Description string `json:"description"`

	// Id 检测项唯一标识（如 tool_call_json_schema）
	Id string `json:"id"`

	// Name 中文显示名
	Name string `json:"name"`

	// NeedsControl 是否需要对照渠道
	NeedsControl bool `json:"needsControl"`

	// NeedsPricing 是否要求目标模型已定价
	NeedsPricing bool `json:"needsPricing"`

	// Protocols 适用协议（渠道须至少声明其中之一）
	Protocols []Protocol `json:"protocols"`

	// RequestsPerCase 每用例请求数（如 toolschema 非流式+流式各一次 = 2），用于前端估算请求量
	RequestsPerCase int `json:"requestsPerCase"`

	// SupportsMaxCases 是否受任务参数「用例数上限」影响（固定请求矩阵的检测项为 false）
	SupportsMaxCases bool `json:"supportsMaxCases"`
}

// ProbeScore defines model for ProbeScore.
type ProbeScore struct {
	Checkpoints []CheckpointScore `json:"checkpoints"`
	ProbeId     string            `json:"probeId"`

	// ProbeName 检测项中文名（快照自注册表；检测项已下架时回退为 id）
	ProbeName string `json:"probeName"`

	// Score 检查点加权平均（0-100）；全部检查点未采样时缺省
	Score *float32 `json:"score,omitempty"`
}

// Protocol 渠道支持的接口协议
type Protocol string

// QualityCaseResult defines model for QualityCaseResult.
type QualityCaseResult struct {
	// Arguments 模型最终产出的工具参数原文（截断存储）
	Arguments  *string `json:"arguments,omitempty"`
	Attempts   int     `json:"attempts"`
	HttpStatus *int    `json:"httpStatus,omitempty"`
	LatencyMs  *int    `json:"latencyMs,omitempty"`

	// Line 套件内行号（1 起，与 KVV 官方报告对齐）
	Line int `json:"line"`

	// Message 失败摘要（校验错误/上游错误体截断；通过时为空）
	Message         string   `json:"message"`
	Mode            CaseMode `json:"mode"`
	Probe           string   `json:"probe"`
	SelectionReason string   `json:"selectionReason"`

	// Status 用例判定：rejected=请求被上游拒绝（HTTP/传输错误）；violated=响应到手但不合规；passed=合规；collected=已采集·待评估（跨行断言检测项运行中的中间态，只含原始计数不含结论，任务结束后必被终态覆盖）
	Status CaseStatus `json:"status"`

	// Suite 语料套件名（如 TestEnforcerCases）
	Suite string `json:"suite"`
}

// QualityExport 证据链自足的 JSON 导出：任务快照 + 评分板 + 全量用例级结果，脱离平台可独立审计
type QualityExport struct {
	// Report 评分板：按「检查点 + 权重」模型即时计算——检查点得分=命中用例通过占比，检测项得分=检查点加权平均，总分=各检测项等权平均。原始判定以用例级结果为准，评分是其视图。
	Report  QualityReport       `json:"report"`
	Results []QualityCaseResult `json:"results"`
	Task    QualityTask         `json:"task"`

	// Tool 固定 "assay"
	Tool string `json:"tool"`

	// Version 导出时服务端版本
	Version string `json:"version"`
}

// QualityReport 评分板：按「检查点 + 权重」模型即时计算——检查点得分=命中用例通过占比，检测项得分=检查点加权平均，总分=各检测项等权平均。原始判定以用例级结果为准，评分是其视图。
type QualityReport struct {
	GeneratedAt time.Time `json:"generatedAt"`

	// Incomplete 任务非正常结束（failed/canceled），评分仅基于已采集数据
	Incomplete *bool        `json:"incomplete,omitempty"`
	Probes     []ProbeScore `json:"probes"`

	// Score 总分 0-100；无任何已采样检查点时缺省
	Score  *float32           `json:"score,omitempty"`
	Status TaskStatus         `json:"status"`
	TaskId openapi_types.UUID `json:"taskId"`
}

// QualityTask defines model for QualityTask.
type QualityTask struct {
	CreatedAt time.Time `json:"createdAt"`

	// CreatedBy 创建者用户名（用户被删后缺省）
	CreatedBy *string `json:"createdBy,omitempty"`

	// Error 任务级失败原因（用例级失败不算任务失败）
	Error         *string            `json:"error,omitempty"`
	FinishedAt    *time.Time         `json:"finishedAt,omitempty"`
	Id            openapi_types.UUID `json:"id"`
	Params        QualityTaskParams  `json:"params"`
	Probes        []string           `json:"probes"`
	ProgressDone  int                `json:"progressDone"`
	ProgressTotal int                `json:"progressTotal"`

	// Score 总分 0-100；仅列表接口对终态任务返回，按当前检查点注册表口径即时计算、绝不持久化；排队/运行中或无已采样检查点时缺省
	Score     *float32   `json:"score,omitempty"`
	StartedAt *time.Time `json:"startedAt,omitempty"`
	Stats     *TaskStats `json:"stats,omitempty"`
	Status    TaskStatus `json:"status"`

	// Target 检测对象参数快照（任务创建时定格，不受渠道后续编辑/删除影响；绝不含 API key）
	Target TaskTarget `json:"target"`
}

// QualityTaskCreate defines model for QualityTaskCreate.
type QualityTaskCreate struct {
	ChannelId    openapi_types.UUID `json:"channelId"`
	ModelEntryId openapi_types.UUID `json:"modelEntryId"`
	Params       *QualityTaskParams `json:"params,omitempty"`

	// Probes 勾选的检测项 id 集合
	Probes []string `json:"probes"`
}

// QualityTaskList defines model for QualityTaskList.
type QualityTaskList struct {
	Items []QualityTask `json:"items"`
	Total int           `json:"total"`
}

// QualityTaskParams defines model for QualityTaskParams.
type QualityTaskParams struct {
	// Concurrency 任务内请求并发数
	Concurrency *int `json:"concurrency,omitempty"`

	// MaxCases 用例数上限（缺省=全量；超过检测项全量数时按全量算）
	MaxCases *int `json:"maxCases,omitempty"`

	// Reruns 失败用例重跑轮数（末次结果为准）
	Reruns *int `json:"reruns,omitempty"`
}

// Role defines model for Role.
type Role struct {
	BuiltIn bool               `json:"builtIn"`
	Id      openapi_types.UUID `json:"id"`
	Name    string             `json:"name"`

	// Permissions 粗粒度模块权限开关：控制对应页面与该模块全部接口的访问
	Permissions PermissionMap `json:"permissions"`
}

// RoleCreate defines model for RoleCreate.
type RoleCreate struct {
	Name string `json:"name"`

	// Permissions 粗粒度模块权限开关：控制对应页面与该模块全部接口的访问
	Permissions PermissionMap `json:"permissions"`
}

// RoleUpdate defines model for RoleUpdate.
type RoleUpdate struct {
	Name *string `json:"name,omitempty"`

	// Permissions 粗粒度模块权限开关：控制对应页面与该模块全部接口的访问
	Permissions *PermissionMap `json:"permissions,omitempty"`
}

// StabilityCalibration 负载画像定标：任务开始先发一条固定字符数的填充请求，读 prompt_tokens 得实测字符/token 比，后续请求按此比例凑长度
type StabilityCalibration struct {
	// CacheWarmCached 写缓存预热的第二条请求实测 cached_tokens（验证共享前缀已写入渠道缓存；无 usage 缺省）
	CacheWarmCached *int `json:"cacheWarmCached,omitempty"`

	// Chars 定标填充字符数
	Chars int `json:"chars"`

	// DeviationPct 实测比相对名义比的偏差（%）
	DeviationPct float32 `json:"deviationPct"`

	// MeasuredRatio 实测字符/token 比
	MeasuredRatio float32 `json:"measuredRatio"`

	// NominalRatio 名义字符/token 比
	NominalRatio float32 `json:"nominalRatio"`

	// PromptTokens 定标请求实测 prompt_tokens
	PromptTokens int `json:"promptTokens"`

	// SharedTokens 共享前缀目标 token 数（缓存命中率 >0 时有）
	SharedTokens *int `json:"sharedTokens,omitempty"`
}

// StabilityDeviation 目标 vs 实测 token 的相对偏差分布（%，正 = 实测多于目标）
type StabilityDeviation struct {
	// AbsP95 |偏差| 的 p95
	AbsP95 float32 `json:"absP95"`

	// Exceeded |偏差| p95 超过 ±10%
	Exceeded bool    `json:"exceeded"`
	Max      float32 `json:"max"`
	Min      float32 `json:"min"`
	P50      float32 `json:"p50"`

	// Samples 参与统计的样本数（正常应答且有 usage）
	Samples int `json:"samples"`
}

// StabilityExport 证据链自足的 JSON 导出：任务快照 + 指标报告 + 全量逐请求样本
type StabilityExport struct {
	// Report 稳定性指标报告：档级 + overall 聚合，口径见 footnotes
	Report  StabilityReport   `json:"report"`
	Samples []StabilitySample `json:"samples"`
	Task    StabilityTask     `json:"task"`
	Tool    string            `json:"tool"`
	Version string            `json:"version"`
}

// StabilityMetrics 一个（probe×档位）的指标集
type StabilityMetrics struct {
	// AchievedRate 开环档实际达成到达率（req/s，在途封顶会低于目标）
	AchievedRate *float32 `json:"achievedRate,omitempty"`

	// AchievedTokenRate TPM 开环档实测 token 吞吐（token/s，输入+输出都计）
	AchievedTokenRate *float32 `json:"achievedTokenRate,omitempty"`

	// BudgetExhausted 输出上限被思考用完、还没写出正文的条数（渠道正常应答，不计入 errors）；这些请求测不到 TTFT
	BudgetExhausted *int `json:"budgetExhausted,omitempty"`

	// ByErrorClass 各错误分类计数
	ByErrorClass *map[string]int `json:"byErrorClass,omitempty"`

	// CacheExpected 目标缓存命中率 h（仅 >0 时有）
	CacheExpected *float32 `json:"cacheExpected,omitempty"`

	// CacheHitRate 实测缓存命中率 = Σcached_tokens / Σinput_tokens（正常应答样本；仅目标命中率 >0 时有）
	CacheHitRate *float32 `json:"cacheHitRate,omitempty"`

	// CacheHits 输入命中缓存的成功条数；不计入延迟分位
	CacheHits *int `json:"cacheHits,omitempty"`

	// CacheMiss 实测命中率偏离目标超过 ±0.10（渠道缓存未按预期命中）
	CacheMiss *bool `json:"cacheMiss,omitempty"`

	// Calibration __overall__ 负载画像定标结果（仅输入塑形时有）
	Calibration *StabilityCalibration `json:"calibration,omitempty"`

	// Concurrency 阶梯并发档的并发数（其它 probe 缺省）
	Concurrency *int `json:"concurrency,omitempty"`

	// ConvergedRpm __overall__ RPM 收敛的可持续边界（请求/分钟）
	ConvergedRpm *float32 `json:"convergedRpm,omitempty"`

	// ConvergedTpm __overall__ TPM 收敛的可持续边界（token/分钟）
	ConvergedTpm *float32 `json:"convergedTpm,omitempty"`

	// ErrorRate 真错误 / 全部请求（输出上限用尽属正常应答，不算错误）
	ErrorRate float32 `json:"errorRate"`
	Errors    int     `json:"errors"`

	// InputDeviation 目标输入 vs 实测 prompt_tokens 的相对偏差分布（仅输入塑形时有）
	InputDeviation *StabilityDeviation `json:"inputDeviation,omitempty"`

	// OutputDeviation 目标输出 vs 实测 completion_tokens 的相对偏差分布（仅有输出目标时有）
	OutputDeviation *StabilityDeviation `json:"outputDeviation,omitempty"`

	// RateLimitHeaders 最近一次响应携带的限速头快照（x-ratelimit-*/anthropic-ratelimit-*/retry-after）
	RateLimitHeaders *map[string]string `json:"rateLimitHeaders,omitempty"`

	// RateLimited 开环档 429 占比是否判定为触发限速
	RateLimited *bool `json:"rateLimited,omitempty"`

	// ReachedCap __overall__ 探到速率护栏顶仍未限速（真实边界≥护栏）
	ReachedCap *bool `json:"reachedCap,omitempty"`

	// ReasoningSeen 正常应答中出现推理增量的条数（请求关闭思考时据此判断是否关掉）
	ReasoningSeen *int `json:"reasoningSeen,omitempty"`

	// Requests 计入统计的请求数（已剔除预热）
	Requests int `json:"requests"`

	// TargetRate 开环档目标到达率（req/s）
	TargetRate *float32 `json:"targetRate,omitempty"`

	// TargetTokenRate TPM 开环档目标 token 到达率（token/s）
	TargetTokenRate *float32 `json:"targetTokenRate,omitempty"`

	// ThroughputRps 达成吞吐（请求/秒，按样本时间窗计）
	ThroughputRps *float32 `json:"throughputRps,omitempty"`

	// TokensPerSec 输出 token 吞吐（token/秒）
	TokensPerSec *float32 `json:"tokensPerSec,omitempty"`

	// TotalMs 一组延迟观测的分位数摘要（评估期确定性计算，单位毫秒）
	TotalMs *StabilityPercentiles `json:"totalMs,omitempty"`

	// Truncated __overall__ RPM/TPM 搜索被全局硬闸截断；未出现限速档时收敛值只是下界，出现过则二分未完成
	Truncated *bool `json:"truncated,omitempty"`

	// TruncatedBy __overall__ 先触发的硬闸
	TruncatedBy *StabilityMetricsTruncatedBy `json:"truncatedBy,omitempty"`

	// TtfbMs 一组延迟观测的分位数摘要（评估期确定性计算，单位毫秒）
	TtfbMs *StabilityPercentiles `json:"ttfbMs,omitempty"`

	// TtfdMs 首个非空增量（推理或正文）耗时分位；推理模型「开始干活」的时刻，非推理模型≈TTFT
	TtfdMs *StabilityPercentiles `json:"ttfdMs,omitempty"`

	// TtftMs 一组延迟观测的分位数摘要（评估期确定性计算，单位毫秒）
	TtftMs *StabilityPercentiles `json:"ttftMs,omitempty"`
}

// StabilityMetricsTruncatedBy __overall__ 先触发的硬闸
type StabilityMetricsTruncatedBy string

// StabilityPercentiles 一组延迟观测的分位数摘要（评估期确定性计算，单位毫秒）
type StabilityPercentiles struct {
	Avg float32 `json:"avg"`
	Max int     `json:"max"`
	Min int     `json:"min"`
	P50 int     `json:"p50"`
	P95 int     `json:"p95"`
	P99 int     `json:"p99"`
}

// StabilityProbeInfo 稳定性检测项元数据（产出性能指标，无评分检查点）
type StabilityProbeInfo struct {
	Description string `json:"description"`

	// EstRequests 按默认参数的最坏预估请求数（前端据实选参数自行重算展示）
	EstRequests int `json:"estRequests"`

	// Id 检测项唯一标识（如 concurrency_ladder）
	Id   string `json:"id"`
	Name string `json:"name"`

	// Protocols 适用协议（空=全适用，前端展示为三协议皆可）
	Protocols []Protocol `json:"protocols"`
}

// StabilityReport 稳定性指标报告：档级 + overall 聚合，口径见 footnotes
type StabilityReport struct {
	// Footnotes 测量口径脚注（TTFT 起点、预热剔除、分位数算法等）
	Footnotes   *[]string `json:"footnotes,omitempty"`
	GeneratedAt time.Time `json:"generatedAt"`

	// Incomplete 任务非正常结束（failed/canceled），指标仅基于已采集样本
	Incomplete *bool `json:"incomplete,omitempty"`

	// Protocol 渠道支持的接口协议
	Protocol Protocol               `json:"protocol"`
	Stages   []StabilityStageMetric `json:"stages"`
	Status   TaskStatus             `json:"status"`
	TaskId   openapi_types.UUID     `json:"taskId"`
}

// StabilitySample 一次压测请求的逐请求原始时序（证据链源；失败样本延迟/计量字段缺省）
type StabilitySample struct {
	// CachedTokens 输入中命中缓存的 token 数
	CachedTokens *int      `json:"cachedTokens,omitempty"`
	DispatchedAt time.Time `json:"dispatchedAt"`
	Error        *string   `json:"error,omitempty"`
	ErrorClass   *string   `json:"errorClass,omitempty"`

	// HttpProto 实际协商的协议版本（如 HTTP/1.1）
	HttpProto    *string `json:"httpProto,omitempty"`
	HttpStatus   *int    `json:"httpStatus,omitempty"`
	InputTokens  *int    `json:"inputTokens,omitempty"`
	Ok           bool    `json:"ok"`
	OutputTokens *int    `json:"outputTokens,omitempty"`
	Probe        string  `json:"probe"`

	// Protocol 渠道支持的接口协议
	Protocol   Protocol `json:"protocol"`
	Seq        int      `json:"seq"`
	Stage      string   `json:"stage"`
	StageIndex int      `json:"stageIndex"`

	// TargetInputTokens 本条请求的目标输入 token（仅输入塑形时有）
	TargetInputTokens *int `json:"targetInputTokens,omitempty"`

	// TargetOutputTokens 本条请求的目标输出 token（有输出目标时有）
	TargetOutputTokens *int `json:"targetOutputTokens,omitempty"`
	TotalMs            *int `json:"totalMs,omitempty"`
	TtfbMs             *int `json:"ttfbMs,omitempty"`

	// TtfdMs 首个非空增量（推理或正文）耗时
	TtfdMs *int `json:"ttfdMs,omitempty"`
	TtftMs *int `json:"ttftMs,omitempty"`
	Warmup bool `json:"warmup"`
}

// StabilityStageMetric 一档（或 __overall__ probe 级）的评估结果
type StabilityStageMetric struct {
	// Metrics 一个（probe×档位）的指标集
	Metrics StabilityMetrics `json:"metrics"`
	Probe   string           `json:"probe"`

	// Stage 档位标识；__overall__ 为 probe 级汇总
	Stage string `json:"stage"`

	// StageIndex 档序号；__overall__ 为 -1
	StageIndex int `json:"stageIndex"`
}

// StabilityTask defines model for StabilityTask.
type StabilityTask struct {
	CreatedAt  time.Time          `json:"createdAt"`
	CreatedBy  *string            `json:"createdBy,omitempty"`
	Error      *string            `json:"error,omitempty"`
	FinishedAt *time.Time         `json:"finishedAt,omitempty"`
	Id         openapi_types.UUID `json:"id"`

	// Params 稳定性任务参数：实选协议 + 各 probe 档位 + 全局成本硬闸
	Params        StabilityTaskParams `json:"params"`
	Probes        []string            `json:"probes"`
	ProgressDone  int                 `json:"progressDone"`
	ProgressTotal int                 `json:"progressTotal"`
	StartedAt     *time.Time          `json:"startedAt,omitempty"`
	Status        TaskStatus          `json:"status"`

	// Target 检测对象参数快照（任务创建时定格，不受渠道后续编辑/删除影响；绝不含 API key）
	Target TaskTarget `json:"target"`
}

// StabilityTaskCreate defines model for StabilityTaskCreate.
type StabilityTaskCreate struct {
	ChannelId    openapi_types.UUID `json:"channelId"`
	ModelEntryId openapi_types.UUID `json:"modelEntryId"`

	// Params 稳定性任务参数：实选协议 + 各 probe 档位 + 全局成本硬闸
	Params StabilityTaskParams `json:"params"`

	// Probes 勾选的稳定性检测项 id 集合
	Probes []string `json:"probes"`
}

// StabilityTaskList defines model for StabilityTaskList.
type StabilityTaskList struct {
	Items []StabilityTask `json:"items"`
	Total int             `json:"total"`
}

// StabilityTaskParams 稳定性任务参数：实选协议 + 各 probe 档位 + 全局成本硬闸
type StabilityTaskParams struct {
	// ConcurrencyLadder 阶梯并发的并发档序列（闭环）
	ConcurrencyLadder *[]int `json:"concurrencyLadder,omitempty"`

	// MaxDurationSec 整任务墙钟上限（秒）；到点停派新请求、在途的跑完，已出结果照常出报告并标截断
	MaxDurationSec *int `json:"maxDurationSec,omitempty"`

	// MaxTotalRequests 全局请求硬闸；累计达到即收敛停止
	MaxTotalRequests *int `json:"maxTotalRequests,omitempty"`

	// MaxTotalTokens 全局 token 硬闸；累计达到即收敛停止
	MaxTotalTokens *int `json:"maxTotalTokens,omitempty"`

	// Protocol 渠道支持的接口协议
	Protocol *Protocol `json:"protocol,omitempty"`

	// RequestTimeoutMs 单请求超时（毫秒）
	RequestTimeoutMs *int `json:"requestTimeoutMs,omitempty"`

	// RequestsPerStage 每档计入统计的请求数
	RequestsPerStage *int `json:"requestsPerStage,omitempty"`

	// RpmBinarySteps 找到限速档后二分细化真实边界的步数
	RpmBinarySteps *int `json:"rpmBinarySteps,omitempty"`

	// RpmLimitThreshold 判定某档触发限速的 429 占比阈值（0-1）
	RpmLimitThreshold *float32 `json:"rpmLimitThreshold,omitempty"`

	// RpmMaxInFlight RPM 在途请求上限（防雪崩兜底）
	RpmMaxInFlight *int `json:"rpmMaxInFlight,omitempty"`

	// RpmMaxRate RPM 探测速率护栏上限（req/s）；升到此仍不限速则报「边界≥上限」
	RpmMaxRate *float32 `json:"rpmMaxRate,omitempty"`

	// RpmStageSec RPM 每档发压时长（秒）；前一半为热身（消化渠道残留计数/突发额度），只用后一半判限速
	RpmStageSec *int `json:"rpmStageSec,omitempty"`

	// RpmStartRate RPM 实测起始到达率（req/s，开环）
	RpmStartRate *float32 `json:"rpmStartRate,omitempty"`

	// TpmBinarySteps 找到限速档后二分细化真实 token 速率边界的步数
	TpmBinarySteps *int `json:"tpmBinarySteps,omitempty"`

	// TpmLimitThreshold 判定某档触发限速的 429 占比阈值（0-1）
	TpmLimitThreshold *float32 `json:"tpmLimitThreshold,omitempty"`

	// TpmMaxInFlight TPM 在途请求上限（防雪崩兜底）
	TpmMaxInFlight *int `json:"tpmMaxInFlight,omitempty"`

	// TpmMaxRate TPM 探测 token 速率护栏上限（token/s）；升到此仍不限速则报「边界≥上限」
	TpmMaxRate *float32 `json:"tpmMaxRate,omitempty"`

	// TpmStageSec TPM 每档发压时长（秒）；前一半为热身，只用后一半判限速
	TpmStageSec *int `json:"tpmStageSec,omitempty"`

	// TpmStartRate TPM 实测起始 token 到达率（token/s，开环；换算请求速率发压）
	TpmStartRate *float32 `json:"tpmStartRate,omitempty"`

	// WarmupPerStage 每档预热请求数（评估时剔除，不计入指标）；缺省 0（不预热）
	WarmupPerStage *int `json:"warmupPerStage,omitempty"`

	// Workload 负载画像：控制每条压测请求的输入 token 数、缓存命中率、输出 token 数。全缺省 = 小输入、不共享前缀、输出沿用各检测项默认
	Workload *StabilityWorkload `json:"workload,omitempty"`
}

// StabilityWorkload 负载画像：控制每条压测请求的输入 token 数、缓存命中率、输出 token 数。全缺省 = 小输入、不共享前缀、输出沿用各检测项默认
type StabilityWorkload struct {
	// CacheHitRate 目标缓存命中率 h（0-0.95）；>0 时每条 prompt 以约 h×输入目标的任务内共享前缀开头，须配合输入塑形且共享前缀 ≥1024 token
	CacheHitRate *float32 `json:"cacheHitRate,omitempty"`

	// DisableThinking 按协议官方参数请求关闭思考（chat 发 thinking.type=disabled、responses 发 reasoning.effort=none、anthropic 发 thinking.type=disabled）；关不掉的照正常应答口径统计并在报告注明
	DisableThinking *bool `json:"disableThinking,omitempty"`

	// Input 每条压测请求的输入 token 目标。none=沿用小 prompt（不塑形）；fixed=固定目标；ramp=按本档排定顺序从 min 匀速涨到 max；jitter=[min,max] 内均匀随机（以任务 ID 做种，可复现）
	Input *StabilityWorkloadInput `json:"input,omitempty"`

	// Output 每请求输出 token 目标：max_tokens=该值并用顶格数数 prompt 诱导写满；缺省 = 各检测项默认（阶梯并发 2048 / RPM 16 / TPM 256）
	Output *int `json:"output,omitempty"`
}

// StabilityWorkloadInput 每条压测请求的输入 token 目标。none=沿用小 prompt（不塑形）；fixed=固定目标；ramp=按本档排定顺序从 min 匀速涨到 max；jitter=[min,max] 内均匀随机（以任务 ID 做种，可复现）
type StabilityWorkloadInput struct {
	// Max ramp/jitter 区间上限（须大于 min）
	Max *int `json:"max,omitempty"`

	// Min ramp/jitter 区间下限
	Min  *int                       `json:"min,omitempty"`
	Mode StabilityWorkloadInputMode `json:"mode"`

	// Value fixed 模式的目标 token 数
	Value *int `json:"value,omitempty"`
}

// StabilityWorkloadInputMode defines model for StabilityWorkloadInput.Mode.
type StabilityWorkloadInputMode string

// TaskStatBucket defines model for TaskStatBucket.
type TaskStatBucket struct {
	// Collected 已采集·待评估行数（仅运行中非零）
	Collected int    `json:"collected"`
	Name      string `json:"name"`
	Passed    int    `json:"passed"`
	Rejected  int    `json:"rejected"`
	Total     int    `json:"total"`
	Violated  int    `json:"violated"`
}

// TaskStats defines model for TaskStats.
type TaskStats struct {
	ByMode []TaskStatBucket `json:"byMode"`

	// ByReason 按选例理由（selection_reason）分桶
	ByReason []TaskStatBucket `json:"byReason"`

	// Collected 已采集·待评估行数（仅运行中非零）
	Collected int `json:"collected"`
	Passed    int `json:"passed"`
	Rejected  int `json:"rejected"`
	Total     int `json:"total"`
	Violated  int `json:"violated"`
}

// TaskStatus defines model for TaskStatus.
type TaskStatus string

// TaskTarget 检测对象参数快照（任务创建时定格，不受渠道后续编辑/删除影响；绝不含 API key）
type TaskTarget struct {
	BaseUrl          string   `json:"baseUrl"`
	CachedInputPrice *float32 `json:"cachedInputPrice,omitempty"`

	// ChannelId 原渠道 id（渠道被删后仅作历史参考）
	ChannelId   *openapi_types.UUID `json:"channelId,omitempty"`
	ChannelName string              `json:"channelName"`

	// Currency 渠道定价币种（仅标注，不做汇率换算）
	Currency     *Currency           `json:"currency,omitempty"`
	InputPrice   *float32            `json:"inputPrice,omitempty"`
	Model        string              `json:"model"`
	ModelEntryId *openapi_types.UUID `json:"modelEntryId,omitempty"`
	OutputPrice  *float32            `json:"outputPrice,omitempty"`
	Protocols    []Protocol          `json:"protocols"`
}

// UpdateStatus defines model for UpdateStatus.
type UpdateStatus struct {
	CurrentVersion string     `json:"currentVersion"`
	LatestVersion  *string    `json:"latestVersion,omitempty"`
	PublishedAt    *time.Time `json:"publishedAt,omitempty"`
	ReleaseNotes   *string    `json:"releaseNotes,omitempty"`

	// TokenConfigured 服务器是否配置了 GitHub Token（未配置时无法检查/触发更新）
	TokenConfigured bool `json:"tokenConfigured"`
	UpdateAvailable bool `json:"updateAvailable"`
}

// User defines model for User.
type User struct {
	AuthSource AuthSource         `json:"authSource"`
	CreatedAt  time.Time          `json:"createdAt"`
	Id         openapi_types.UUID `json:"id"`
	RoleId     openapi_types.UUID `json:"roleId"`
	RoleName   string             `json:"roleName"`
	Username   string             `json:"username"`
}

// UserCreate defines model for UserCreate.
type UserCreate struct {
	Password string             `json:"password"`
	RoleId   openapi_types.UUID `json:"roleId"`
	Username string             `json:"username"`
}

// UserUpdate defines model for UserUpdate.
type UserUpdate struct {
	Password *string             `json:"password,omitempty"`
	RoleId   *openapi_types.UUID `json:"roleId,omitempty"`
}

// VersionInfo defines model for VersionInfo.
type VersionInfo struct {
	Version string `json:"version"`
}

// IdPath defines model for IdPath.
type IdPath = openapi_types.UUID

// ModelIdPath defines model for ModelIdPath.
type ModelIdPath = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// FeishuAuthorizeParams defines parameters for FeishuAuthorize.
type FeishuAuthorizeParams struct {
	// Next 登录成功后要回到的站内路径（如 /quality/abc）。只接受以单个 / 开头的相对路径， 其余一律忽略并回落到首页——防开放重定向。
	Next *string `form:"next,omitempty" json:"next,omitempty"`
}

// FeishuCallbackParams defines parameters for FeishuCallback.
type FeishuCallbackParams struct {
	// Code 授权码，5 分钟有效且仅可用一次
	Code *string `form:"code,omitempty" json:"code,omitempty"`

	// State 发起授权时下发的一次性随机串
	State *string `form:"state,omitempty" json:"state,omitempty"`

	// Error 用户取消授权等失败场景由飞书回传
	Error *string `form:"error,omitempty" json:"error,omitempty"`
}

// GetChannelConnectivityHistoryParams defines parameters for GetChannelConnectivityHistory.
type GetChannelConnectivityHistoryParams struct {
	// Hours 回看窗口小时数
	Hours *int `form:"hours,omitempty" json:"hours,omitempty"`
}

// ListQualityTasksParams defines parameters for ListQualityTasks.
type ListQualityTasksParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Status 按任务状态筛选；缺省不过滤
	Status *TaskStatus `form:"status,omitempty" json:"status,omitempty"`

	// ChannelId 按渠道筛选；缺省不过滤（渠道删除后其任务 channel_id 置空，仅在不过滤时可见）
	ChannelId *openapi_types.UUID `form:"channelId,omitempty" json:"channelId,omitempty"`
}

// ExportQualityTaskParams defines parameters for ExportQualityTask.
type ExportQualityTaskParams struct {
	Format ExportQualityTaskParamsFormat `form:"format" json:"format"`
}

// ExportQualityTaskParamsFormat defines parameters for ExportQualityTask.
type ExportQualityTaskParamsFormat string

// ListQualityTaskResultsParams defines parameters for ListQualityTaskResults.
type ListQualityTaskResultsParams struct {
	Status *CaseStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListStabilityTasksParams defines parameters for ListStabilityTasks.
type ListStabilityTasksParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Status 按任务状态筛选；缺省不过滤
	Status *TaskStatus `form:"status,omitempty" json:"status,omitempty"`

	// ChannelId 按渠道筛选；缺省不过滤（渠道删除后其任务 channel_id 置空，仅在不过滤时可见）
	ChannelId *openapi_types.UUID `form:"channelId,omitempty" json:"channelId,omitempty"`
}

// ExportStabilityTaskParams defines parameters for ExportStabilityTask.
type ExportStabilityTaskParams struct {
	Format ExportStabilityTaskParamsFormat `form:"format" json:"format"`
}

// ExportStabilityTaskParamsFormat defines parameters for ExportStabilityTask.
type ExportStabilityTaskParamsFormat string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ChangeOwnPasswordJSONRequestBody defines body for ChangeOwnPassword for application/json ContentType.
type ChangeOwnPasswordJSONRequestBody = ChangePasswordRequest

// CreateChannelJSONRequestBody defines body for CreateChannel for application/json ContentType.
type CreateChannelJSONRequestBody = ChannelCreate

// UpdateChannelJSONRequestBody defines body for UpdateChannel for application/json ContentType.
type UpdateChannelJSONRequestBody = ChannelUpdate

// AddChannelModelJSONRequestBody defines body for AddChannelModel for application/json ContentType.
type AddChannelModelJSONRequestBody = ModelEntryUpsert

// UpdateChannelModelJSONRequestBody defines body for UpdateChannelModel for application/json ContentType.
type UpdateChannelModelJSONRequestBody = ModelEntryUpsert

// TestChannelJSONRequestBody defines body for TestChannel for application/json ContentType.
type TestChannelJSONRequestBody = ConnectivityTestRequest

// CreateQualityTaskJSONRequestBody defines body for CreateQualityTask for application/json ContentType.
type CreateQualityTaskJSONRequestBody = QualityTaskCreate

// CreateRoleJSONRequestBody defines body for CreateRole for application/json ContentType.
type CreateRoleJSONRequestBody = RoleCreate

// UpdateRoleJSONRequestBody defines body for UpdateRole for application/json ContentType.
type UpdateRoleJSONRequestBody = RoleUpdate

// CreateStabilityTaskJSONRequestBody defines body for CreateStabilityTask for application/json ContentType.
type CreateStabilityTaskJSONRequestBody = StabilityTaskCreate

// TriggerDeployJSONRequestBody defines body for TriggerDeploy for application/json ContentType.
type TriggerDeployJSONRequestBody = DeployRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = UserCreate

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UserUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// FeishuAuthorize 跳转飞书授权页（下发一次性 state Cookie 防 CSRF）
	// (GET /auth/feishu/authorize)
	FeishuAuthorize(w http.ResponseWriter, r *http.Request, params FeishuAuthorizeParams)
	// FeishuCallback 飞书授权回调：换取用户身份、建立会话后跳回首页
	// (GET /auth/feishu/callback)
	FeishuCallback(w http.ResponseWriter, r *http.Request, params FeishuCallbackParams)
	// Login 登录，成功后通过 HttpOnly Cookie 建立会话
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout 登出，销毁当前会话
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// GetCurrentUser 获取当前登录用户（含角色与模块权限）
	// (GET /auth/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// GetAuthMethods 查询本站启用了哪些登录方式（登录页据此渲染，无需鉴权）
	// (GET /auth/methods)
	GetAuthMethods(w http.ResponseWriter, r *http.Request)
	// ChangeOwnPassword 修改自己的密码（需验证当前密码，成功后注销其他会话）
	// (PUT /auth/password)
	ChangeOwnPassword(w http.ResponseWriter, r *http.Request)
	// ListChannels 渠道列表（需 channels 权限）
	// (GET /channels)
	ListChannels(w http.ResponseWriter, r *http.Request)
	// CreateChannel 创建渠道（需 channels 权限；模型条目建完后在详情页添加）
	// (POST /channels)
	CreateChannel(w http.ResponseWriter, r *http.Request)
	// DeleteChannel 删除渠道（需 channels 权限；硬删，历史任务持有参数快照不受影响，key 不可恢复）
	// (DELETE /channels/{id})
	DeleteChannel(w http.ResponseWriter, r *http.Request, id IdPath)
	// GetChannel 渠道详情（需 channels 权限；含模型条目列表）
	// (GET /channels/{id})
	GetChannel(w http.ResponseWriter, r *http.Request, id IdPath)
	// UpdateChannel 修改渠道基本信息（需 channels 权限；apiKey 缺省=不改、给值=覆盖，写后不可回读）
	// (PATCH /channels/{id})
	UpdateChannel(w http.ResponseWriter, r *http.Request, id IdPath)
	// GetChannelConnectivityHistory 连通历史（登录即可；总览延迟曲线数据源，含手动测试与定时探活两种来源）
	// (GET /channels/{id}/connectivity/history)
	GetChannelConnectivityHistory(w http.ResponseWriter, r *http.Request, id IdPath, params GetChannelConnectivityHistoryParams)
	// AddChannelModel 添加模型条目（需 channels 权限）
	// (POST /channels/{id}/models)
	AddChannelModel(w http.ResponseWriter, r *http.Request, id IdPath)
	// DeleteChannelModel 删除模型条目（需 channels 权限；历史任务持有参数快照不受影响）
	// (DELETE /channels/{id}/models/{modelId})
	DeleteChannelModel(w http.ResponseWriter, r *http.Request, id IdPath, modelId ModelIdPath)
	// UpdateChannelModel 全量替换模型条目（需 channels 权限；缺省的价格字段即清空为未定价）
	// (PUT /channels/{id}/models/{modelId})
	UpdateChannelModel(w http.ResponseWriter, r *http.Request, id IdPath, modelId ModelIdPath)
	// TestChannel 连通测试（需 channels 权限；对每个已声明协议发 max_tokens=1 最小真实请求，结果落库为该渠道最近一次测试）
	// (POST /channels/{id}/test)
	TestChannel(w http.ResponseWriter, r *http.Request, id IdPath)
	// GetHealthz 健康检查
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// ListOverviewChannels 总览渠道卡片（登录即可；渠道基本信息 + 各模型最近终态质量任务得分，得分即时计算不持久化）
	// (GET /overview/channels)
	ListOverviewChannels(w http.ResponseWriter, r *http.Request)
	// ListProbes 检测项注册表（需 quality 权限；含元数据供发起页勾选）
	// (GET /probes)
	ListProbes(w http.ResponseWriter, r *http.Request)
	// ListQualityTasks 质量检测任务历史（需 quality 权限；按创建时间倒序，可按状态/渠道筛选）
	// (GET /quality/tasks)
	ListQualityTasks(w http.ResponseWriter, r *http.Request, params ListQualityTasksParams)
	// CreateQualityTask 创建质量检测任务（需 quality 权限；创建时快照检测对象参数，入队后由 worker 执行）
	// (POST /quality/tasks)
	CreateQualityTask(w http.ResponseWriter, r *http.Request)
	// GetQualityTask 任务详情（需 quality 权限；含参数快照与聚合统计）
	// (GET /quality/tasks/{id})
	GetQualityTask(w http.ResponseWriter, r *http.Request, id IdPath)
	// CancelQualityTask 取消任务（需 quality 权限；排队或运行中的任务可取消，运行中的中止在途请求）
	// (POST /quality/tasks/{id}/cancel)
	CancelQualityTask(w http.ResponseWriter, r *http.Request, id IdPath)
	// StreamQualityTaskEvents 任务进度事件流（需 quality 权限；SSE，连接后先推当前快照，任务终态后关闭）
	// (GET /quality/tasks/{id}/events)
	StreamQualityTaskEvents(w http.ResponseWriter, r *http.Request, id IdPath)
	// ExportQualityTask 导出报告（需 quality 权限；json=证据链自足报告，junit=JUnit XML；仅终态任务可用）
	// (GET /quality/tasks/{id}/export)
	ExportQualityTask(w http.ResponseWriter, r *http.Request, id IdPath, params ExportQualityTaskParams)
	// GetQualityTaskReport 评分板（需 quality 权限；检查点加权评分，按当前注册表口径即时计算，仅终态任务可用）
	// (GET /quality/tasks/{id}/report)
	GetQualityTaskReport(w http.ResponseWriter, r *http.Request, id IdPath)
	// ListQualityTaskResults 用例级结果（需 quality 权限；可按判定状态过滤）
	// (GET /quality/tasks/{id}/results)
	ListQualityTaskResults(w http.ResponseWriter, r *http.Request, id IdPath, params ListQualityTaskResultsParams)
	// ListRoles 角色列表（需 users 权限）
	// (GET /roles)
	ListRoles(w http.ResponseWriter, r *http.Request)
	// CreateRole 创建角色（需 users 权限）
	// (POST /roles)
	CreateRole(w http.ResponseWriter, r *http.Request)
	// DeleteRole 删除角色（需 users 权限；内置角色与仍被使用的角色不可删除）
	// (DELETE /roles/{id})
	DeleteRole(w http.ResponseWriter, r *http.Request, id IdPath)
	// UpdateRole 修改角色名或权限（需 users 权限；内置角色不可修改）
	// (PATCH /roles/{id})
	UpdateRole(w http.ResponseWriter, r *http.Request, id IdPath)
	// ListStabilityProbes 稳定性检测项注册表（需 stability 权限；产出性能指标，无评分检查点）
	// (GET /stability/probes)
	ListStabilityProbes(w http.ResponseWriter, r *http.Request)
	// ListStabilityTasks 稳定性检测任务历史（需 stability 权限；按创建时间倒序，可按状态/渠道筛选）
	// (GET /stability/tasks)
	ListStabilityTasks(w http.ResponseWriter, r *http.Request, params ListStabilityTasksParams)
	// CreateStabilityTask 创建稳定性检测任务（需 stability 权限；创建时快照检测对象+协议，入队后由 worker 发压）
	// (POST /stability/tasks)
	CreateStabilityTask(w http.ResponseWriter, r *http.Request)
	// GetStabilityTask 稳定性任务详情（需 stability 权限；含参数快照）
	// (GET /stability/tasks/{id})
	GetStabilityTask(w http.ResponseWriter, r *http.Request, id IdPath)
	// CancelStabilityTask 取消稳定性任务（需 stability 权限；排队或运行中的任务可取消，运行中的中止在途请求）
	// (POST /stability/tasks/{id}/cancel)
	CancelStabilityTask(w http.ResponseWriter, r *http.Request, id IdPath)
	// StreamStabilityTaskEvents 稳定性任务进度事件流（需 stability 权限；SSE，连接后先推当前快照，任务终态后关闭）
	// (GET /stability/tasks/{id}/events)
	StreamStabilityTaskEvents(w http.ResponseWriter, r *http.Request, id IdPath)
	// ExportStabilityTask 导出稳定性报告（需 stability 权限；json=证据链自足报告，含全量逐请求样本；仅终态任务可用）
	// (GET /stability/tasks/{id}/export)
	ExportStabilityTask(w http.ResponseWriter, r *http.Request, id IdPath, params ExportStabilityTaskParams)
	// GetStabilityTaskMetrics 稳定性指标报告（需 stability 权限；档级+overall 聚合，仅终态任务可用）
	// (GET /stability/tasks/{id}/metrics)
	GetStabilityTaskMetrics(w http.ResponseWriter, r *http.Request, id IdPath)
	// GetUpdateStatus 检查在线更新（需 system 权限；查询 GitHub 最新 Release）
	// (GET /system/update)
	GetUpdateStatus(w http.ResponseWriter, r *http.Request)
	// TriggerDeploy 触发在线更新（需 system 权限；调 GitHub Actions 重新部署指定版本）
	// (POST /system/update/deploy)
	TriggerDeploy(w http.ResponseWriter, r *http.Request)
	// ListUsers 用户列表（需 users 权限）
	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request)
	// CreateUser 创建用户（需 users 权限；不开放注册，账号只能在此创建）
	// (POST /users)
	CreateUser(w http.ResponseWriter, r *http.Request)
	// DeleteUser 删除用户（需 users 权限；不能删除自己）
	// (DELETE /users/{id})
	DeleteUser(w http.ResponseWriter, r *http.Request, id IdPath)
	// UpdateUser 修改用户角色或重置密码（需 users 权限；不能改自己的角色）
	// (PATCH /users/{id})
	UpdateUser(w http.ResponseWriter, r *http.Request, id IdPath)
	// GetVersion 当前服务版本
	// (GET /version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// FeishuAuthorize operation middleware
func (siw *ServerInterfaceWrapper) FeishuAuthorize(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params FeishuAuthorizeParams

	// ------------- Optional query parameter "next" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "next", r.URL.Query(), &params.Next, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "next"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "next", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FeishuAuthorize(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FeishuCallback operation middleware
func (siw *ServerInterfaceWrapper) FeishuCallback(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params FeishuCallbackParams

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "code", r.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "error" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "error", r.URL.Query(), &params.Error, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "error"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FeishuCallback(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthMethods operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMethods(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthMethods(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ChangeOwnPassword operation middleware
func (siw *ServerInterfaceWrapper) ChangeOwnPassword(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChangeOwnPassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListChannels operation middleware
func (siw *ServerInterfaceWrapper) ListChannels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListChannels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateChannel operation middleware
func (siw *ServerInterfaceWrapper) CreateChannel(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateChannel(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteChannel operation middleware
func (siw *ServerInterfaceWrapper) DeleteChannel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteChannel(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChannel operation middleware
func (siw *ServerInterfaceWrapper) GetChannel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChannel(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateChannel operation middleware
func (siw *ServerInterfaceWrapper) UpdateChannel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateChannel(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChannelConnectivityHistory operation middleware
func (siw *ServerInterfaceWrapper) GetChannelConnectivityHistory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetChannelConnectivityHistoryParams

	// ------------- Optional query parameter "hours" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "hours", r.URL.Query(), &params.Hours, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "hours"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hours", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChannelConnectivityHistory(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddChannelModel operation middleware
func (siw *ServerInterfaceWrapper) AddChannelModel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddChannelModel(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteChannelModel operation middleware
func (siw *ServerInterfaceWrapper) DeleteChannelModel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "modelId" -------------
	var modelId ModelIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "modelId", r.PathValue("modelId"), &modelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "modelId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteChannelModel(w, r, id, modelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateChannelModel operation middleware
func (siw *ServerInterfaceWrapper) UpdateChannelModel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "modelId" -------------
	var modelId ModelIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "modelId", r.PathValue("modelId"), &modelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "modelId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateChannelModel(w, r, id, modelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TestChannel operation middleware
func (siw *ServerInterfaceWrapper) TestChannel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TestChannel(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOverviewChannels operation middleware
func (siw *ServerInterfaceWrapper) ListOverviewChannels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOverviewChannels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProbes operation middleware
func (siw *ServerInterfaceWrapper) ListProbes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProbes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListQualityTasks operation middleware
func (siw *ServerInterfaceWrapper) ListQualityTasks(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListQualityTasksParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "channelId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "channelId", r.URL.Query(), &params.ChannelId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "channelId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListQualityTasks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateQualityTask operation middleware
func (siw *ServerInterfaceWrapper) CreateQualityTask(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateQualityTask(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetQualityTask operation middleware
func (siw *ServerInterfaceWrapper) GetQualityTask(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetQualityTask(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelQualityTask operation middleware
func (siw *ServerInterfaceWrapper) CancelQualityTask(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelQualityTask(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamQualityTaskEvents operation middleware
func (siw *ServerInterfaceWrapper) StreamQualityTaskEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamQualityTaskEvents(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportQualityTask operation middleware
func (siw *ServerInterfaceWrapper) ExportQualityTask(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportQualityTaskParams

	// ------------- Required query parameter "format" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "format", r.URL.Query(), &params.Format, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "format"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "format", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportQualityTask(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetQualityTaskReport operation middleware
func (siw *ServerInterfaceWrapper) GetQualityTaskReport(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetQualityTaskReport(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListQualityTaskResults operation middleware
func (siw *ServerInterfaceWrapper) ListQualityTaskResults(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListQualityTaskResultsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListQualityTaskResults(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRoles operation middleware
func (siw *ServerInterfaceWrapper) ListRoles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRoles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRole operation middleware
func (siw *ServerInterfaceWrapper) CreateRole(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRole(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteRole operation middleware
func (siw *ServerInterfaceWrapper) DeleteRole(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRole(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRole operation middleware
func (siw *ServerInterfaceWrapper) UpdateRole(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRole(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListStabilityProbes operation middleware
func (siw *ServerInterfaceWrapper) ListStabilityProbes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListStabilityProbes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListStabilityTasks operation middleware
func (siw *ServerInterfaceWrapper) ListStabilityTasks(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListStabilityTasksParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "channelId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "channelId", r.URL.Query(), &params.ChannelId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "channelId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListStabilityTasks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateStabilityTask operation middleware
func (siw *ServerInterfaceWrapper) CreateStabilityTask(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateStabilityTask(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStabilityTask operation middleware
func (siw *ServerInterfaceWrapper) GetStabilityTask(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStabilityTask(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelStabilityTask operation middleware
func (siw *ServerInterfaceWrapper) CancelStabilityTask(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelStabilityTask(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamStabilityTaskEvents operation middleware
func (siw *ServerInterfaceWrapper) StreamStabilityTaskEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamStabilityTaskEvents(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportStabilityTask operation middleware
func (siw *ServerInterfaceWrapper) ExportStabilityTask(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportStabilityTaskParams

	// ------------- Required query parameter "format" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "format", r.URL.Query(), &params.Format, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "format"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "format", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportStabilityTask(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStabilityTaskMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetStabilityTaskMetrics(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStabilityTaskMetrics(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUpdateStatus operation middleware
func (siw *ServerInterfaceWrapper) GetUpdateStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUpdateStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerDeploy operation middleware
func (siw *ServerInterfaceWrapper) TriggerDeploy(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerDeploy(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/version", wrapper.GetVersion)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/login", wrapper.Login)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/logout", wrapper.Logout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/me", wrapper.GetCurrentUser)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/auth/password", wrapper.ChangeOwnPassword)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/methods", wrapper.GetAuthMethods)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/feishu/authorize", wrapper.FeishuAuthorize)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/feishu/callback", wrapper.FeishuCallback)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/users", wrapper.ListUsers)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/users", wrapper.CreateUser)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/users/{id}", wrapper.DeleteUser)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/users/{id}", wrapper.UpdateUser)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/roles", wrapper.ListRoles)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/roles", wrapper.CreateRole)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/roles/{id}", wrapper.DeleteRole)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/roles/{id}", wrapper.UpdateRole)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/channels", wrapper.ListChannels)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/channels", wrapper.CreateChannel)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/channels/{id}", wrapper.DeleteChannel)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/channels/{id}", wrapper.GetChannel)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/channels/{id}", wrapper.UpdateChannel)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/channels/{id}/models", wrapper.AddChannelModel)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/channels/{id}/models/{modelId}", wrapper.DeleteChannelModel)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/channels/{id}/models/{modelId}", wrapper.UpdateChannelModel)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/channels/{id}/test", wrapper.TestChannel)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/channels/{id}/connectivity/history", wrapper.GetChannelConnectivityHistory)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/overview/channels", wrapper.ListOverviewChannels)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/system/update", wrapper.GetUpdateStatus)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/system/update/deploy", wrapper.TriggerDeploy)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/probes", wrapper.ListProbes)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/quality/tasks", wrapper.ListQualityTasks)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/quality/tasks", wrapper.CreateQualityTask)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/quality/tasks/{id}", wrapper.GetQualityTask)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/quality/tasks/{id}/results", wrapper.ListQualityTaskResults)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/quality/tasks/{id}/report", wrapper.GetQualityTaskReport)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/quality/tasks/{id}/export", wrapper.ExportQualityTask)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/quality/tasks/{id}/cancel", wrapper.CancelQualityTask)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/quality/tasks/{id}/events", wrapper.StreamQualityTaskEvents)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/stability/probes", wrapper.ListStabilityProbes)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/stability/tasks", wrapper.ListStabilityTasks)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/stability/tasks", wrapper.CreateStabilityTask)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/stability/tasks/{id}", wrapper.GetStabilityTask)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/stability/tasks/{id}/metrics", wrapper.GetStabilityTaskMetrics)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/stability/tasks/{id}/export", wrapper.ExportStabilityTask)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/stability/tasks/{id}/cancel", wrapper.CancelStabilityTask)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/stability/tasks/{id}/events", wrapper.StreamStabilityTaskEvents)

	return m
}
